#!/bin/sh
set -eu

if [ "${CARGO_PROFILE_DEV_DEBUG+x}" != x ]; then
    export CARGO_PROFILE_DEV_DEBUG=0
fi

exec uv run --locked --project dev pre-commit hook-impl \
    --config .pre-commit-config.yaml \
    --hook-type pre-commit \
    --hook-dir .githooks \
    -- "$@"
