//! Check of the walk tree of a `search` answer.
//!
//! A hit is a walk hit when its target is `symbol` and its `traversal_path` has a hop. The walk
//! hits form one tree per starting symbol; every other hit is an item. The tree is rebuilt here
//! from the structured answer alone, then the text is checked against it:
//!
//! - Roots come in the order their first walk hit appears; the nodes under a node come in the
//!   order their first walk hit appears. Walk hits that share a prefix of hops share its nodes,
//!   and the last hop of a path never lands on a node that already is a hit.
//! - A hit outside the walk with the symbol identity of a root is that root and is no item.
//! - A root sits at one level. A node at depth `d` writes its head line `↳ <relationship>` alone
//!   at `1 + d` levels and its further lines at `2 + d` levels. A root indents every line by one
//!   level. A root that is a hit writes its declaration with no word before it, then `in <facts>`
//!   and `at <symbol identity>` as a branch does; a root that is no hit writes `at <identity>`.
//! - A blank line precedes every node except the first entry of the section.
//! - A node without a hit writes `at <symbol identity>` and no other line. A node with a hit
//!   writes the declaration, `in <facts>`, `at <symbol identity>`, and the further lines of a
//!   symbol hit, without `relationship` among the matched fields. The declaration starts with
//!   `by ` exactly when every facet phrase of the hop ends in ` by`; the head line then leaves
//!   that ` by` out of each phrase. The facts start with `in ` exactly when they start with a
//!   location.

use serde_json::Value;

use super::{
    Item, SECTION_LEVELS, SEPARATOR, indent, located_states, place_of, require, score_states,
    source_may_end_blank, source_states, text_at, visible,
};

/// Mark that starts a node under the root.
const BRANCH: &str = "↳";
/// Word before the declaration of a node when the relationship ends in `by`.
const BY: &str = "by ";
/// Ending of a phrase that moves to the declaration line.
const BY_ENDING: &str = " by";
/// Word before the facts of a node that start with a location.
const IN: &str = "in ";
/// Word before the symbol identity of a node.
const AT: &str = "at ";
/// Word before the first facet of a heuristic relationship.
const HEURISTIC: &str = "probably ";
/// Matched field that the tree states, so the facts line leaves it out.
const STATED_FIELD: &str = "relationship";
/// Each relationship facet, read from the target back to the source.
const INCOMING: [(&str, &str); 29] = [
    ("contains", "contained by"),
    ("declares", "declared by"),
    ("augments", "augmented by"),
    ("references", "referenced by"),
    ("calls", "called by"),
    ("constructs", "constructed by"),
    ("reads", "read by"),
    ("writes", "written by"),
    ("imports", "imported by"),
    ("exports", "exported by"),
    ("extends", "extended by"),
    ("implements", "implemented by"),
    ("has_type", "type of"),
    ("overrides", "overridden by"),
    ("aliases", "aliased by"),
    ("generates", "generated by"),
    ("depends_on", "dependency of"),
    ("annotated_by", "annotates"),
    ("throws", "thrown by"),
    ("catches", "caught by"),
    ("bounded_by", "bounds"),
    ("instantiates", "instantiated by"),
    ("specializes", "specialized by"),
    ("overloads", "overloaded by"),
    ("mixes_in", "mixed in by"),
    ("embeds", "embedded by"),
    ("tests", "tested by"),
    ("configures", "configured by"),
    ("binds", "bound by"),
];

/// One hop of a `traversal_path`.
struct Hop {
    /// Identity of the symbol the hop starts from.
    start: String,
    /// Identity of the symbol the hop reaches.
    reached: String,
    /// The head line of the node: `↳ probably called, referenced`.
    head: String,
    /// Whether every facet phrase ends in ` by`, so the declaration line starts with `by `.
    by: bool,
}

/// One symbol of the tree.
struct Node {
    id: String,
    /// Levels under the root.
    depth: usize,
    /// `↳ <relationship>`, empty for a root.
    lead: String,
    /// Whether the declaration line starts with `by `.
    by: bool,
    /// Index in `results` of the hit that is this symbol.
    hit: Option<usize>,
    /// Index in `results` of the first walk hit whose path holds this node.
    origin: usize,
    /// Places, among the nodes, of the nodes directly under this one, in answer order.
    children: Vec<usize>,
}

/// The lines of one node of the text, from its head line.
pub(super) struct NodeLines<'e> {
    node: usize,
    lines: Vec<&'e str>,
}

/// The tree of an answer, and the hits that are items.
pub(super) struct Plan<'a> {
    results: &'a [Value],
    outside: Vec<(usize, &'a Value)>,
    nodes: Vec<Node>,
    roots: Vec<usize>,
}

/// Whether `hit` is a walk hit.
fn is_walk(hit: &Value) -> bool {
    text_at(hit, "/hit/target") == Some("symbol")
        && hit
            .get("traversal_path")
            .and_then(Value::as_array)
            .is_some_and(|hops| !hops.is_empty())
}

/// The hops of the walk hit `hit`.
fn hops_of(hit: &Value, at: &str) -> Result<Vec<Hop>, String> {
    let mut hops = Vec::new();
    for (index, hop) in hit
        .get("traversal_path")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .enumerate()
    {
        let at = format!("{at}[{index}]");
        let text = |pointer: &str| {
            text_at(hop, pointer)
                .map(str::to_owned)
                .ok_or_else(|| format!("{at}{pointer}: must be a string"))
        };
        let (from, to) = (text("/relationship/from")?, text("/relationship/to")?);
        let outgoing = match text("/direction")?.as_str() {
            "outgoing" => true,
            "incoming" => false,
            other => return Err(format!("{at}.direction: unknown direction `{other}`")),
        };
        let mut phrases = Vec::new();
        for facet in hop
            .pointer("/relationship/facets")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .filter_map(Value::as_str)
        {
            phrases.push(if outgoing {
                facet.replace('_', " ")
            } else {
                INCOMING
                    .iter()
                    .find(|(wire, _)| *wire == facet)
                    .map(|(_, phrase)| (*phrase).to_owned())
                    .ok_or_else(|| format!("{at}.relationship.facets: unknown facet `{facet}`"))?
            });
        }
        let guess = if text_at(hop, "/relationship/derivation") == Some("heuristic") {
            HEURISTIC
        } else {
            ""
        };
        let by = !phrases.is_empty() && phrases.iter().all(|phrase| phrase.ends_with(BY_ENDING));
        if by {
            for phrase in &mut phrases {
                phrase.truncate(phrase.len() - BY_ENDING.len());
            }
        }
        let (start, reached) = if outgoing { (from, to) } else { (to, from) };
        hops.push(Hop {
            start,
            reached,
            head: format!("{BRANCH} {guess}{}", phrases.join(", ")),
            by,
        });
    }
    Ok(hops)
}

/// Levels that indent the head line of a node.
fn head_levels(depth: usize) -> usize {
    SECTION_LEVELS + depth
}

/// Levels that indent the further lines of a node. A root has no head line of its own.
fn rest_levels(depth: usize) -> usize {
    if depth == 0 {
        SECTION_LEVELS
    } else {
        SECTION_LEVELS + 1 + depth
    }
}

impl<'a> Plan<'a> {
    /// Splits `results` into items and, when `with_tree`, the tree of its walk hits.
    pub(super) fn of(results: &'a [Value], with_tree: bool) -> Result<Self, String> {
        let mut plan = Self {
            results,
            outside: Vec::new(),
            nodes: Vec::new(),
            roots: Vec::new(),
        };
        for (index, hit) in results.iter().enumerate() {
            if with_tree && is_walk(hit) {
                let hops = hops_of(hit, &format!("$.results[{index}].traversal_path"))?;
                plan.reach(index, &hops);
            } else {
                plan.outside.push((index, hit));
            }
        }
        plan.claim_roots();
        Ok(plan)
    }

    /// The hits written as items, with their index in `results`.
    pub(super) fn outside(&self) -> &[(usize, &'a Value)] {
        &self.outside
    }

    /// Adds the path of the walk hit `index` and puts the hit at its last node.
    fn reach(&mut self, index: usize, hops: &[Hop]) {
        let Some(first) = hops.first() else {
            return;
        };
        let known = self.roots.iter().copied().find(|root| {
            self.nodes
                .get(*root)
                .is_some_and(|node| node.id == first.start)
        });
        let mut place = known.unwrap_or_else(|| {
            self.nodes.push(Node {
                id: first.start.clone(),
                depth: 0,
                lead: String::new(),
                by: false,
                hit: None,
                origin: index,
                children: Vec::new(),
            });
            self.roots.push(self.nodes.len() - 1);
            self.nodes.len() - 1
        });
        for (position, hop) in hops.iter().enumerate() {
            let last = position + 1 == hops.len();
            let parent = place;
            let existing = self.nodes[parent].children.iter().copied().find(|child| {
                let node = &self.nodes[*child];
                node.id == hop.reached && !(last && node.hit.is_some())
            });
            place = existing.unwrap_or_else(|| {
                let depth = self.nodes[parent].depth + 1;
                self.nodes.push(Node {
                    id: hop.reached.clone(),
                    depth,
                    lead: hop.head.clone(),
                    by: hop.by,
                    hit: None,
                    origin: index,
                    children: Vec::new(),
                });
                let place = self.nodes.len() - 1;
                self.nodes[parent].children.push(place);
                place
            });
        }
        self.nodes[place].hit = Some(index);
    }

    /// Moves the hit outside the walk that is the symbol of a root into that root.
    fn claim_roots(&mut self) {
        for root in self.roots.clone() {
            let id = self.nodes[root].id.clone();
            let found = self.outside.iter().position(|(_, hit)| {
                text_at(hit, "/hit/target") == Some("symbol")
                    && text_at(hit, "/hit/symbol/id") == Some(id.as_str())
            });
            if let Some(found) = found {
                self.nodes[root].hit = Some(self.outside.remove(found).0);
            }
        }
    }

    /// The nodes in the order the text writes them: each node before the nodes under it.
    fn order(&self) -> Vec<usize> {
        let mut order = Vec::new();
        let mut pending: Vec<usize> = self.roots.iter().rev().copied().collect();
        while let Some(place) = pending.pop() {
            order.push(place);
            pending.extend(self.nodes[place].children.iter().rev());
        }
        order
    }

    /// The JSON path that names a node.
    fn at(&self, place: usize) -> String {
        let node = &self.nodes[place];
        let hop = node.depth.saturating_sub(1);
        format!("$.results[{}].traversal_path[{hop}]", node.origin)
    }

    /// The identity the node writes: the one of its hit when it has one, else its own.
    fn identity_of<'n>(&'n self, node: &'n Node) -> Option<&'n str> {
        match node.hit {
            Some(index) => text_at(&self.results[index], "/hit/symbol/id"),
            None => Some(node.id.as_str()),
        }
    }

    /// The index in `entries` of the head line of the node `place`, at or after `cursor`.
    fn head_of(&self, place: usize, entries: &[&str], cursor: usize) -> Result<usize, String> {
        let node = &self.nodes[place];
        let at = self.at(place);
        let id = visible(&node.id);
        if node.depth > 0 {
            let opening = format!("{}{}", indent(head_levels(node.depth)), node.lead);
            // The identity line tells two nodes with the same head line apart.
            let identity = self
                .identity_of(node)
                .map(|id| format!("{}{AT}{}", indent(rest_levels(node.depth)), visible(id)));
            let found = (cursor..entries.len()).find(|line| {
                entries[*line] == opening
                    && identity.as_ref().is_none_or(|identity| {
                        entries[*line + 1..]
                            .iter()
                            .take_while(|text| !text.is_empty())
                            .any(|text| text == identity)
                    })
            });
            return found.ok_or_else(|| {
                format!("{at}: no line opens the node with `{opening}` and the identity `{id}`")
            });
        }
        // The identity line is the only line of a root without a hit, and the line after the
        // declaration and the facts of a root with one.
        let anchor = format!("{}{AT}{id}", indent(SECTION_LEVELS));
        let line = (cursor..entries.len())
            .find(|line| entries[*line] == anchor)
            .ok_or_else(|| format!("{at}: no line equals the root `{anchor}`"))?;
        if node.hit.is_none() {
            return Ok(line);
        }
        [2, 1]
            .into_iter()
            .filter_map(|back| line.checked_sub(back))
            .find(|head| {
                *head >= cursor
                    && entries[*head..line].iter().all(|text| !text.is_empty())
                    && (*head == 0 || entries[*head - 1].is_empty())
            })
            .ok_or_else(|| {
                format!("{at}: the root must open with its declaration, after a blank line")
            })
    }

    /// Splits `entries` into the lines of the items and the lines of each node.
    ///
    /// The blank line before the first node belongs to neither.
    pub(super) fn split<'e>(
        &self,
        entries: &[&'e str],
    ) -> Result<(Vec<&'e str>, Vec<NodeLines<'e>>), String> {
        let order = self.order();
        if order.is_empty() {
            return Ok((entries.to_vec(), Vec::new()));
        }
        let mut heads: Vec<usize> = Vec::with_capacity(order.len());
        let mut cursor = 0;
        for place in &order {
            let head = self.head_of(*place, entries, cursor)?;
            heads.push(head);
            cursor = head + 1;
        }
        if self.outside.is_empty() {
            require(heads[0] == 0, "$.results", || {
                "no line may come before the first node".to_owned()
            })?;
        }
        let mut nodes = Vec::with_capacity(order.len());
        for (position, place) in order.iter().enumerate() {
            let head = heads[position];
            require(
                head == 0 || entries[head - 1].is_empty(),
                &self.at(*place),
                || format!("a blank line must precede the node `{}`", entries[head]),
            )?;
            let end = heads
                .get(position + 1)
                .map_or(entries.len(), |next| next - 1);
            nodes.push(NodeLines {
                node: *place,
                lines: entries[head..end].to_vec(),
            });
        }
        Ok((entries[..heads[0].saturating_sub(1)].to_vec(), nodes))
    }

    /// Checks the lines of every node.
    pub(super) fn states(&self, nodes: &[NodeLines<'_>]) -> Result<(), String> {
        for chunk in nodes {
            self.node_states(chunk)?;
        }
        Ok(())
    }

    /// Checks one node: its head, its indents, and the lines of its hit.
    fn node_states(&self, chunk: &NodeLines<'_>) -> Result<(), String> {
        let node = &self.nodes[chunk.node];
        let at = self.at(chunk.node);
        let rest = rest_levels(node.depth);
        if node.depth > 0 && node.hit.is_none() {
            let identity = format!("{}{AT}{}", indent(rest), visible(&node.id));
            return require(
                chunk.lines == [chunk.lines[0], identity.as_str()],
                &at,
                || {
                    format!(
                        "a node without a hit writes `{AT}{}` and no other line",
                        node.id
                    )
                },
            );
        }
        let Some(index) = node.hit else {
            return require(chunk.lines.len() == 1, &at, || {
                "a root without a hit writes `at <identity>` and no further line".to_owned()
            });
        };
        let hit = &self.results[index];
        let hit_at = format!("$.results[{index}]");
        require(
            chunk.lines.len() < 2
                || chunk.lines.last() != Some(&"")
                || source_may_end_blank(hit.get("source")),
            &hit_at,
            || "a blank line may not end a node, before the next node or section".to_owned(),
        )?;
        let mut item = if node.depth == 0 {
            let head = chunk
                .lines
                .first()
                .and_then(|line| line.strip_prefix(indent(SECTION_LEVELS).as_str()))
                .ok_or_else(|| format!("{at}: the root head must be indented by one level"))?;
            require(!marked(head), &hit_at, || {
                format!("a node takes no marker, got `{head}`")
            })?;
            Item::node(&chunk.lines, head, rest, &hit_at)?
        } else {
            let declaration = chunk
                .lines
                .get(1)
                .and_then(|line| line.strip_prefix(indent(rest).as_str()))
                .ok_or_else(|| {
                    format!("{at}: the declaration must be indented by {rest} levels")
                })?;
            let item = Item::node(&chunk.lines[1..], declaration, rest, &hit_at)?;
            require(declaration.starts_with(BY) == node.by, &at, || {
                format!(
                    "the declaration `{declaration}` must start with `{BY}` exactly when every facet ends in `{BY_ENDING}`"
                )
            })?;
            item
        };
        Self::strip_words(&mut item, hit, &hit_at)?;
        let facts: Vec<&str> = item.plain(1).split(SEPARATOR).collect();
        score_states(&facts, hit, &hit_at)?;
        located_states(&item, &facts, hit, "symbol", &hit_at, Some(STATED_FIELD))?;
        source_after_blank(&item, hit.get("source"), &hit_at)?;
        source_states(&item, hit.get("source"), &hit_at)
    }

    /// Removes `in ` from the facts line and `at ` from the identity line of a node under the
    /// root, after checking that they are there exactly when the node states them.
    fn strip_words(item: &mut Item<'_>, hit: &Value, at: &str) -> Result<(), String> {
        let located = place_of(
            text_at(hit, "/path"),
            text_at(hit, "/unit"),
            hit.get("line").and_then(Value::as_u64),
        )
        .is_some();
        let facts = item.plain(1);
        match (located, facts.strip_prefix(IN)) {
            (true, Some(rest)) => item.lines[1] = rest,
            (true, None) => {
                return Err(format!("{at}: the facts `{facts}` must start with `{IN}`"));
            }
            (false, Some(_)) => {
                return Err(format!(
                    "{at}: the facts `{facts}` have no location, so no `{IN}`"
                ));
            }
            (false, None) => {}
        }
        if let Some(id) = text_at(hit, "/hit/symbol/id") {
            let written = format!("{AT}{}", visible(id));
            require(
                !item.lines.iter().skip(1).any(|line| *line == id),
                at,
                || format!("the identity `{id}` must start with `{AT}`"),
            )?;
            let position = item.lines.iter().position(|line| *line == written);
            let position =
                position.ok_or_else(|| format!("{at}.hit: no line equals `{written}`"))?;
            item.lines[position] = item.lines[position].strip_prefix(AT).unwrap_or_default();
        }
        Ok(())
    }
}

/// Whether `head` starts with an item marker such as `[2]`.
fn marked(head: &str) -> bool {
    head.strip_prefix('[')
        .and_then(|rest| rest.split_once(']'))
        .is_some_and(|(number, _)| !number.is_empty() && number.bytes().all(|b| b.is_ascii_digit()))
}

/// Checks that the source of a node follows a blank line.
fn source_after_blank(item: &Item<'_>, source: Option<&Value>, at: &str) -> Result<(), String> {
    let Some(source) = source
        .and_then(Value::as_str)
        .filter(|source| !source.is_empty())
    else {
        return Ok(());
    };
    let expected: Vec<&str> = source.split('\n').collect();
    let after_blank = item
        .lines
        .windows(expected.len())
        .position(|window| window == expected)
        .is_some_and(|start| start > 0 && item.lines.get(start - 1) == Some(&""));
    require(after_blank, &format!("{at}.source"), || {
        "the source must follow a blank line".to_owned()
    })
}
