//! `scope` on `get_symbol` and `search` end to end: a served workspace whose `Cargo.toml`
//! names a path dependency, and the lookups that reach that package's public
//! declarations.
//!
//! The first read whose `scope` reaches packages analyzes the workspace's packages on
//! this machine and answers from what it built, so every suite here reads once and
//! proves the scopes against the analyzed package.

mod hermetic_search;
// `workspace_client` carries the shared served-workspace scaffolding; this binary drives
// one tool, so it uses part of it.
#[allow(dead_code)]
mod workspace_client;

use std::fs;

use serde_json::{Value, json};
use workspace_client::{
    ServedWorkspace, TestResult, call_retrying_acceptance, served_workspace, tool_request,
};

/// The unit every helper declaration is served under.
const HELPER_UNIT: &str = "rift://source/cargo/helper@0.1.0/src/lib.rs";

/// The helper crate: public declarations and one private one.
///
/// `helper_lantern` is documented and named nothing like its documentation, so
/// only a full-text ranking over the package's own documents reaches it.
const HELPER_SOURCE: &str = "pub fn helper_beacon() {}\nfn helper_private() {}\npub fn beacon() {}\n/// Signals the harbour pilots at dusk.\npub fn helper_lantern() {}\n";

/// A second helper source file, so the crate selects two files and a `package_files`
/// bound of one refuses it.
const HELPER_EXTRA_SOURCE: &str = "pub fn helper_extra() {}\n";

/// A v4 lockfile naming the project and its path dependency: what
/// `cargo metadata --locked --offline` accepts without the network and without
/// rewriting the file.
const LOCK_WITH_HELPER: &str = "\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = \"helper\"
version = \"0.1.0\"

[[package]]
name = \"probe\"
version = \"0.1.0\"
dependencies = [
 \"helper\",
]
";

/// A served workspace beside the helper crate it depends on.
struct DependentWorkspace {
    /// The helper's directory, held for the life of the server: the catalog roots the
    /// package there, and a dropped tempdir would leave nothing to index.
    _helper: tempfile::TempDir,
    served: ServedWorkspace,
}

/// Lays the helper crate out in its own directory and serves a project that depends on it
/// by path, with `configuration` appended to the served `rift.toml`. The path is spelled
/// as a TOML literal string, so no separator needs escaping.
async fn served_dependent_workspace(configuration: Option<&str>) -> TestResult<DependentWorkspace> {
    let helper = tempfile::tempdir()?;
    fs::create_dir_all(helper.path().join("src"))?;
    fs::write(
        helper.path().join("Cargo.toml"),
        "[package]\nname = \"helper\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )?;
    fs::write(helper.path().join("src/lib.rs"), HELPER_SOURCE)?;
    fs::write(helper.path().join("src/extra.rs"), HELPER_EXTRA_SOURCE)?;
    let manifest = format!(
        "[package]\nname = \"probe\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n\
         [dependencies]\nhelper = {{ path = '{}' }}\n",
        helper.path().display()
    );
    let served = served_workspace(
        &[
            ("Cargo.toml", manifest.as_str()),
            ("Cargo.lock", LOCK_WITH_HELPER),
            ("src/lib.rs", "pub fn beacon() {}\n"),
        ],
        configuration.map(str::to_owned),
    )
    .await?;
    Ok(DependentWorkspace {
        _helper: helper,
        served,
    })
}

/// One `get_symbol` answer for `arguments`.
async fn get_symbol(
    client: &rmcp::service::RunningService<rmcp::RoleClient, ()>,
    arguments: Value,
) -> TestResult<Value> {
    call_retrying_acceptance(client, tool_request("get_symbol", &arguments)).await
}

/// One `search` answer for `arguments`.
async fn search(
    client: &rmcp::service::RunningService<rmcp::RoleClient, ()>,
    arguments: Value,
) -> TestResult<Value> {
    call_retrying_acceptance(client, tool_request("search", &arguments)).await
}

/// The wire `ErrorData` one refused `tool` call carries. The caller has already proven
/// the workspace answers, so the refusal is the request's own rather than acceptance's.
async fn refused_call(
    client: &rmcp::service::RunningService<rmcp::RoleClient, ()>,
    tool: &'static str,
    arguments: Value,
) -> TestResult<Value> {
    let error = client
        .call_tool(tool_request(tool, &arguments))
        .await
        .expect_err("the request must be refused");
    let rmcp::ServiceError::McpError(data) = error else {
        panic!("expected protocol-level McpError, got {error:?}");
    };
    Ok(data.data.ok_or("wire error data must be present")?)
}

/// The wire `ErrorData` one refused `search` carries.
async fn refused_search(
    client: &rmcp::service::RunningService<rmcp::RoleClient, ()>,
    arguments: Value,
) -> TestResult<Value> {
    refused_call(client, "search", arguments).await
}

/// Each symbol hit's declaration name and whether it is addressed by `unit`.
fn located_names(answer: &Value) -> Vec<(String, bool)> {
    answer["results"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|hit| {
            hit["hit"]["symbol"]["name"]
                .as_str()
                .map(str::to_owned)
                .map(|name| (name, hit.get("unit").is_some()))
        })
        .collect()
}

/// The helper lookup, which analyzes the workspace's packages on its first call.
///
/// An empty answer means the package could not be analyzed, and the warnings say why;
/// reading again would change nothing, so this fails at once rather than retrying.
async fn helper_indexed(
    client: &rmcp::service::RunningService<rmcp::RoleClient, ()>,
) -> TestResult<Value> {
    let answer = get_symbol(
        client,
        json!({ "name": "helper_beacon", "scope": "global" }),
    )
    .await?;
    if answer["hits"]
        .as_array()
        .is_some_and(|hits| !hits.is_empty())
    {
        return Ok(answer);
    }
    Err(format!("the helper was not analyzed: {answer:#}").into())
}

/// Every hit names exactly one of `path` and `unit`.
fn assert_one_location(hit: &Value) {
    assert_ne!(
        hit.get("path").is_some(),
        hit.get("unit").is_some(),
        "a hit carries exactly one of path and unit: {hit:#}"
    );
}

#[tokio::test]
async fn a_global_lookup_answers_the_package_declaration() -> TestResult {
    let workspace = served_dependent_workspace(None).await?;
    let (_directory, client, server_task) = workspace.served;

    let answer = helper_indexed(&client).await?;

    let hits = answer["hits"].as_array().ok_or("hits are an array")?;
    assert_eq!(hits.len(), 1, "{answer:#}");
    let hit = &hits[0];
    assert_one_location(hit);
    assert_eq!(hit["unit"], json!(HELPER_UNIT), "{hit:#}");
    assert_eq!(hit["symbol"]["name"], json!("helper_beacon"), "{hit:#}");
    assert_eq!(
        hit["symbol"]["origin"]["location"],
        json!("dependency"),
        "{hit:#}"
    );
    assert_eq!(
        hit["symbol"]["origin"]["package"],
        json!({ "manager": "cargo", "name": "helper", "version": "0.1.0" }),
        "{hit:#}"
    );
    assert_eq!(hit["line"], json!(1), "{hit:#}");
    assert!(
        hit["source"]
            .as_str()
            .is_some_and(|source| source.contains("pub fn helper_beacon")),
        "the default include attaches the declaration excerpt: {hit:#}"
    );
    assert!(hit.get("history").is_none(), "{hit:#}");
    assert!(
        answer["warnings"]
            .as_array()
            .into_iter()
            .flatten()
            .all(|warning| warning["package"]["name"] != json!("helper")),
        "an indexed package is never reported skipped: {answer:#}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

/// The catalog resolves the served project itself beside the package it depends on, and
/// the fill analyzes what the dependency context names. The project is not one of them,
/// so `beacon`, declared in both trees, answers a `global` read from the package alone.
#[tokio::test]
async fn a_global_lookup_leaves_the_served_project_out_of_the_packages() -> TestResult {
    let workspace = served_dependent_workspace(None).await?;
    let (_directory, client, server_task) = workspace.served;
    helper_indexed(&client).await?;

    let answer = get_symbol(&client, json!({ "name": "beacon", "scope": "global" })).await?;

    let hits = answer["hits"].as_array().ok_or("hits are an array")?;
    assert!(!hits.is_empty(), "{answer:#}");
    assert!(
        hits.iter().all(|hit| hit["unit"] == json!(HELPER_UNIT)),
        "every package hit comes from the analyzed dependency: {answer:#}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

/// A lockfile naming a registry package no cache on this machine holds: the fill counts
/// it as unresolved, analyzes nothing for it, and the fallback warning states the count
/// beside the packages it did analyze.
#[tokio::test]
async fn a_package_with_no_source_on_this_machine_is_counted_unresolved() -> TestResult {
    let helper = tempfile::tempdir()?;
    fs::create_dir_all(helper.path().join("src"))?;
    fs::write(
        helper.path().join("Cargo.toml"),
        "[package]\nname = \"helper\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )?;
    fs::write(helper.path().join("src/lib.rs"), HELPER_SOURCE)?;
    let manifest = format!(
        "[package]\nname = \"probe\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n\
         [dependencies]\nhelper = {{ path = '{}' }}\nabsent-probe = \"9.9.9\"\n",
        helper.path().display()
    );
    let lockfile = format!(
        "{LOCK_WITH_HELPER}\n[[package]]\nname = \"absent-probe\"\nversion = \"9.9.9\"\n\
         source = \"registry+https://github.com/rust-lang/crates.io-index\"\n"
    );
    let (_directory, client, server_task) = served_workspace(
        &[
            ("Cargo.toml", manifest.as_str()),
            ("Cargo.lock", lockfile.as_str()),
            ("src/lib.rs", "pub fn beacon() {}\n"),
        ],
        None,
    )
    .await?;

    let answer = get_symbol(
        &client,
        json!({ "name": "helper_beacon", "scope": "global" }),
    )
    .await?;

    let detail = answer["warnings"]
        .as_array()
        .into_iter()
        .flatten()
        .find(|warning| warning["code"] == json!("global_index_unavailable"))
        .and_then(|warning| warning["detail"].as_str())
        .ok_or_else(|| format!("a package read states its fallback: {answer:#}"))?;
    assert!(
        detail.contains("1 named no source this machine holds"),
        "{detail}"
    );

    client.cancel().await?;
    server_task.abort();
    Ok(())
}

#[tokio::test]
async fn a_private_declaration_is_not_served() -> TestResult {
    let workspace = served_dependent_workspace(None).await?;
    let (_directory, client, server_task) = workspace.served;
    helper_indexed(&client).await?;

    let answer = get_symbol(
        &client,
        json!({ "name": "helper_private", "scope": "global" }),
    )
    .await?;
    assert_eq!(answer["hits"], json!([]), "{answer:#}");
    assert_eq!(answer["pagination"]["total_pages"], json!(0), "{answer:#}");

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn the_local_scope_leaves_the_package_out() -> TestResult {
    let workspace = served_dependent_workspace(None).await?;
    let (_directory, client, server_task) = workspace.served;
    helper_indexed(&client).await?;

    for arguments in [
        json!({ "name": "helper_beacon" }),
        json!({ "name": "helper_beacon", "scope": "local" }),
    ] {
        let answer = get_symbol(&client, arguments.clone()).await?;
        assert_eq!(answer["hits"], json!([]), "{arguments} {answer:#}");
        assert!(
            answer.get("warnings").is_none(),
            "a package warning rides only an answer whose scope reaches packages: \
             {arguments} {answer:#}"
        );
    }

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn the_all_scope_lists_the_local_hit_before_the_package_hit() -> TestResult {
    let workspace = served_dependent_workspace(None).await?;
    let (_directory, client, server_task) = workspace.served;
    helper_indexed(&client).await?;

    let answer = get_symbol(
        &client,
        json!({ "name": "beacon", "scope": "all", "limit": 10 }),
    )
    .await?;
    let hits = answer["hits"].as_array().ok_or("hits are an array")?;
    assert!(hits.len() >= 2, "{answer:#}");
    for hit in hits {
        assert_one_location(hit);
    }
    assert_eq!(hits[0]["path"], json!("src/lib.rs"), "{answer:#}");
    assert_eq!(hits[0]["symbol"]["name"], json!("beacon"), "{answer:#}");
    assert_eq!(hits[1]["unit"], json!(HELPER_UNIT), "{answer:#}");
    assert_eq!(hits[1]["symbol"]["name"], json!("beacon"), "{answer:#}");

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn a_global_search_answers_the_package_declaration_by_unit() -> TestResult {
    let workspace = served_dependent_workspace(None).await?;
    let (_directory, client, server_task) = workspace.served;
    helper_indexed(&client).await?;

    let answer = search(
        &client,
        json!({ "query": "helper_beacon", "scope": "global" }),
    )
    .await?;

    let results = answer["results"].as_array().ok_or("results are an array")?;
    // The precise phase places the declaration the query names; the widened phase
    // then fills the pool with the package's other `helper` declarations, which is
    // the same order the project's own store answers in.
    let hit = &results[0];
    assert_one_location(hit);
    assert_eq!(hit["unit"], json!(HELPER_UNIT), "{hit:#}");
    // The identifier ranking placed it by name and the package's own full-text
    // ranking placed it again through the signature and the declaration source.
    assert_eq!(
        hit["matched_by"],
        json!(["name", "signature", "content"]),
        "{hit:#}"
    );
    assert_eq!(hit["hit"]["target"], json!("symbol"), "{hit:#}");
    assert_eq!(
        hit["hit"]["symbol"]["name"],
        json!("helper_beacon"),
        "{hit:#}"
    );
    assert_eq!(
        hit["hit"]["symbol"]["origin"]["location"],
        json!("dependency"),
        "{hit:#}"
    );
    assert_eq!(hit["line"], json!(1), "{hit:#}");
    assert!(
        hit.get("source").is_none() && hit.get("score").is_none(),
        "an omitted include attaches neither excerpt nor score: {hit:#}"
    );
    assert!(
        hit.get("traversal_path").is_none() && hit.get("distance").is_none(),
        "a lexical hit carries no walk: {hit:#}"
    );
    assert!(
        answer["warnings"]
            .as_array()
            .into_iter()
            .flatten()
            .all(|warning| warning["package"]["name"] != json!("helper")),
        "an indexed package is never reported skipped: {answer:#}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn the_all_scope_search_answers_local_and_package_hits() -> TestResult {
    let workspace = served_dependent_workspace(None).await?;
    let (_directory, client, server_task) = workspace.served;
    helper_indexed(&client).await?;

    let answer = search(
        &client,
        json!({
            "query": "beacon",
            "scope": "all",
            "target": "symbol",
            "include": ["source"],
            "limit": 10
        }),
    )
    .await?;

    let located = located_names(&answer);
    for expected in [
        ("beacon".to_owned(), false),
        ("beacon".to_owned(), true),
        ("helper_beacon".to_owned(), true),
    ] {
        assert!(located.contains(&expected), "{expected:?} {answer:#}");
    }
    let results = answer["results"].as_array().ok_or("results are an array")?;
    for hit in results {
        assert_one_location(hit);
        assert!(hit["source"].is_string(), "{hit:#}");
    }
    let project = results
        .iter()
        .find(|hit| hit.get("path").is_some())
        .ok_or("the project hit is addressed by path")?;
    assert_eq!(project["path"], json!("src/lib.rs"), "{project:#}");

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn a_global_search_reaches_a_package_declaration_through_its_documentation() -> TestResult {
    // The query shares no word with the declaration's name, so the identifier
    // ranking cannot place it. Only the package's own full-text ranking can,
    // which is the input this scope gained.
    let workspace = served_dependent_workspace(None).await?;
    let (_directory, client, server_task) = workspace.served;
    helper_indexed(&client).await?;

    let answer = search(
        &client,
        json!({ "query": "harbour pilots", "scope": "global" }),
    )
    .await?;

    let results = answer["results"].as_array().ok_or("results are an array")?;
    assert_eq!(results.len(), 1, "{answer:#}");
    let hit = &results[0];
    assert_eq!(hit["unit"], json!(HELPER_UNIT), "{hit:#}");
    assert_eq!(
        hit["hit"]["symbol"]["name"],
        json!("helper_lantern"),
        "{hit:#}"
    );
    // The declaration's own source carries the doc comment too, so both columns
    // placed it.
    assert_eq!(
        hit["matched_by"],
        json!(["documentation", "content"]),
        "{hit:#}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn a_global_search_with_traversal_refuses_invalid_request() -> TestResult {
    let workspace = served_dependent_workspace(None).await?;
    let (_directory, client, server_task) = workspace.served;
    search(&client, json!({ "query": "beacon" })).await?;

    let wire = refused_search(
        &client,
        json!({
            "query": "beacon",
            "scope": "global",
            "traversal": { "seed": "rift://symbol/rust/src/lib.rs/beacon" }
        }),
    )
    .await?;

    assert_eq!(wire["code"], json!("invalid_request"), "{wire:#}");
    assert!(
        wire["message"]
            .as_str()
            .is_some_and(|message| message.contains("traversal")),
        "the refusal names the field: {wire:#}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn a_revision_search_with_a_global_scope_refuses_invalid_request() -> TestResult {
    let workspace = served_dependent_workspace(None).await?;
    let (directory, client, server_task) = workspace.served;
    // A committed baseline, so `main` resolves and the scope rule is what refuses; the
    // workspace database stays out of the commit.
    fs::write(directory.path().join(".gitignore"), ".rift/\n")?;
    rift_history::fixture::init(directory.path());
    rift_history::fixture::commit_all(directory.path(), "fixture baseline");
    search(&client, json!({ "query": "beacon" })).await?;

    let wire = refused_search(
        &client,
        json!({ "query": "beacon", "scope": "all", "rev": "main" }),
    )
    .await?;

    assert_eq!(wire["code"], json!("invalid_request"), "{wire:#}");
    assert!(
        wire["message"]
            .as_str()
            .is_some_and(|message| message.contains("scope")),
        "the refusal names the field: {wire:#}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

/// The `package_skipped` warning naming the helper, which the first package read
/// records when its bounds refuse the package.
async fn helper_skipped(
    client: &rmcp::service::RunningService<rmcp::RoleClient, ()>,
) -> TestResult<Value> {
    let answer = get_symbol(
        client,
        json!({ "name": "helper_beacon", "scope": "global" }),
    )
    .await?;
    assert!(
        answer["hits"].as_array().is_some_and(Vec::is_empty),
        "a refused package answers no hit: {answer:#}"
    );
    answer["warnings"]
        .as_array()
        .into_iter()
        .flatten()
        .find(|warning| {
            warning["code"] == json!("package_skipped")
                && warning["package"]["name"] == json!("helper")
        })
        .cloned()
        .ok_or_else(|| format!("the refusal names the helper: {answer:#}").into())
}

/// A `package_files` bound the helper crosses records a refusal; raising the bound in
/// `rift.toml` analyzes the package again on the next read, since every package the
/// branch holds was read under the old bounds.
#[tokio::test]
async fn raising_package_files_after_a_refusal_reindexes_on_the_next_request() -> TestResult {
    let workspace = served_dependent_workspace(Some("[dependencies]\npackage_files = 1\n")).await?;
    let (directory, client, server_task) = workspace.served;
    let skipped = helper_skipped(&client).await?;
    assert!(
        skipped["reason"]
            .as_str()
            .is_some_and(|reason| reason.contains("package_files_max=1")),
        "the refusal names the bound: {skipped:#}"
    );

    fs::write(
        directory.path().join("rift.toml"),
        format!(
            "{}[dependencies]\npackage_files = 2000\n",
            hermetic_search::VECTOR_DISABLED
        ),
    )?;
    let answer = call_retrying_acceptance(
        &client,
        tool_request(
            "get_symbol",
            &json!({ "name": "helper_beacon", "scope": "global" }),
        ),
    )
    .await?;

    let hits = answer["hits"].as_array().ok_or("hits are an array")?;
    assert_eq!(hits.len(), 1, "{answer:#}");
    assert_eq!(
        hits[0]["symbol"]["name"],
        json!("helper_beacon"),
        "{answer:#}"
    );
    assert!(
        answer["warnings"]
            .as_array()
            .into_iter()
            .flatten()
            .all(|warning| warning["package"]["name"] != json!("helper")),
        "the replanned index holds the helper without a refusal: {answer:#}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}
