//! `scope` on `get_symbol` and `search` end to end: a served workspace whose `Cargo.toml`
//! names a path dependency, and the lookups that reach that package's public
//! declarations.
//!
//! The dependency lane indexes the package behind the answers, so a lookup issued before
//! its pass ends answers empty and carries `dependency_index_pending`; every suite here
//! polls under a bound until the hit appears, then proves the scopes against the indexed
//! package.

mod hermetic_search;
// `workspace_client` carries the shared served-workspace scaffolding; this binary drives
// one tool, so it uses part of it.
#[allow(dead_code)]
mod workspace_client;

use std::fs;
use std::time::Duration;

use serde_json::{Value, json};
use workspace_client::{
    ServedWorkspace, TestResult, call_retrying_acceptance, served_workspace, tool_request,
};

/// Most lookups one suite issues while the lane still indexes the helper.
const INDEX_ATTEMPTS_MAX: usize = 60;
/// Pause between two lookups.
const INDEX_POLL: Duration = Duration::from_millis(250);

/// The unit every helper declaration is served under.
const HELPER_UNIT: &str = "rift://source/cargo/helper@0.1.0/src/lib.rs";

/// The helper crate: two public declarations and one private one.
const HELPER_SOURCE: &str =
    "pub fn helper_beacon() {}\nfn helper_private() {}\npub fn beacon() {}\n";

/// A v4 lockfile naming the project and its path dependency: what
/// `cargo metadata --locked --offline` accepts without the network and without
/// rewriting the file.
const LOCK_WITH_HELPER: &str = "\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = \"helper\"
version = \"0.1.0\"

[[package]]
name = \"probe\"
version = \"0.1.0\"
dependencies = [
 \"helper\",
]
";

/// A served workspace beside the helper crate it depends on.
struct DependentWorkspace {
    /// The helper's directory, held for the life of the server: the catalog roots the
    /// package there, and a dropped tempdir would leave nothing to index.
    _helper: tempfile::TempDir,
    served: ServedWorkspace,
}

/// Lays the helper crate out in its own directory and serves a project that depends on it
/// by path. The path is spelled as a TOML literal string, so no separator needs escaping.
async fn served_dependent_workspace() -> TestResult<DependentWorkspace> {
    let helper = tempfile::tempdir()?;
    fs::create_dir_all(helper.path().join("src"))?;
    fs::write(
        helper.path().join("Cargo.toml"),
        "[package]\nname = \"helper\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )?;
    fs::write(helper.path().join("src/lib.rs"), HELPER_SOURCE)?;
    let manifest = format!(
        "[package]\nname = \"probe\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n\
         [dependencies]\nhelper = {{ path = '{}' }}\n",
        helper.path().display()
    );
    let served = served_workspace(
        &[
            ("Cargo.toml", manifest.as_str()),
            ("Cargo.lock", LOCK_WITH_HELPER),
            ("src/lib.rs", "pub fn beacon() {}\n"),
        ],
        None,
    )
    .await?;
    Ok(DependentWorkspace {
        _helper: helper,
        served,
    })
}

/// One `get_symbol` answer for `arguments`.
async fn get_symbol(
    client: &rmcp::service::RunningService<rmcp::RoleClient, ()>,
    arguments: Value,
) -> TestResult<Value> {
    call_retrying_acceptance(client, tool_request("get_symbol", &arguments)).await
}

/// One `search` answer for `arguments`.
async fn search(
    client: &rmcp::service::RunningService<rmcp::RoleClient, ()>,
    arguments: Value,
) -> TestResult<Value> {
    call_retrying_acceptance(client, tool_request("search", &arguments)).await
}

/// The wire `ErrorData` one refused `search` carries. The caller has already proven the
/// workspace answers, so the refusal is the request's own rather than acceptance's.
async fn refused_search(
    client: &rmcp::service::RunningService<rmcp::RoleClient, ()>,
    arguments: Value,
) -> TestResult<Value> {
    let error = client
        .call_tool(tool_request("search", &arguments))
        .await
        .expect_err("the request must be refused");
    let rmcp::ServiceError::McpError(data) = error else {
        panic!("expected protocol-level McpError, got {error:?}");
    };
    Ok(data.data.ok_or("wire error data must be present")?)
}

/// Each symbol hit's declaration name and whether it is addressed by `unit`.
fn located_names(answer: &Value) -> Vec<(String, bool)> {
    answer["results"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|hit| {
            hit["hit"]["symbol"]["name"]
                .as_str()
                .map(str::to_owned)
                .map(|name| (name, hit.get("unit").is_some()))
        })
        .collect()
}

/// The `code` of every warning the answer carries.
fn warning_codes(answer: &Value) -> Vec<&str> {
    answer["warnings"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|warning| warning["code"].as_str())
        .collect()
}

/// Polls the helper lookup until the lane has indexed the package, and returns that
/// answer.
///
/// An empty answer carries `dependency_index_pending` while the pass runs. One that names
/// a skipped package or a degraded resolver, or warns of nothing at all, fails the poll at
/// once: waiting longer would change nothing.
async fn helper_indexed(
    client: &rmcp::service::RunningService<rmcp::RoleClient, ()>,
) -> TestResult<Value> {
    for _attempt in 0..INDEX_ATTEMPTS_MAX {
        let answer = get_symbol(
            client,
            json!({ "name": "helper_beacon", "scope": "dependencies" }),
        )
        .await?;
        if answer["hits"]
            .as_array()
            .is_some_and(|hits| !hits.is_empty())
        {
            return Ok(answer);
        }
        let codes = warning_codes(&answer);
        if codes.contains(&"dependency_package_skipped")
            || codes.contains(&"dependency_resolver_degraded")
        {
            return Err(format!("the helper cannot be indexed: {answer:#}").into());
        }
        assert!(
            codes.contains(&"dependency_index_pending"),
            "an empty answer while the lane runs names the pending packages: {answer:#}"
        );
        tokio::time::sleep(INDEX_POLL).await;
    }
    Err("the dependency lane never indexed the helper within the poll bound".into())
}

/// Every hit names exactly one of `path` and `unit`.
fn assert_one_location(hit: &Value) {
    assert_ne!(
        hit.get("path").is_some(),
        hit.get("unit").is_some(),
        "a hit carries exactly one of path and unit: {hit:#}"
    );
}

#[tokio::test]
async fn a_dependency_scoped_lookup_answers_the_package_declaration() -> TestResult {
    let workspace = served_dependent_workspace().await?;
    let (_directory, client, server_task) = workspace.served;

    let answer = helper_indexed(&client).await?;

    let hits = answer["hits"].as_array().ok_or("hits are an array")?;
    assert_eq!(hits.len(), 1, "{answer:#}");
    let hit = &hits[0];
    assert_one_location(hit);
    assert_eq!(hit["unit"], json!(HELPER_UNIT), "{hit:#}");
    assert_eq!(hit["symbol"]["name"], json!("helper_beacon"), "{hit:#}");
    assert_eq!(
        hit["symbol"]["origin"]["location"],
        json!("dependency"),
        "{hit:#}"
    );
    assert_eq!(
        hit["symbol"]["origin"]["package"],
        json!({ "manager": "cargo", "name": "helper", "version": "0.1.0" }),
        "{hit:#}"
    );
    assert_eq!(hit["line"], json!(1), "{hit:#}");
    assert!(
        hit["source"]
            .as_str()
            .is_some_and(|source| source.contains("pub fn helper_beacon")),
        "the default include attaches the declaration excerpt: {hit:#}"
    );
    assert!(hit.get("history").is_none(), "{hit:#}");
    assert!(
        answer["warnings"]
            .as_array()
            .into_iter()
            .flatten()
            .all(|warning| warning["package"]["name"] != json!("helper")),
        "an indexed package is never reported skipped: {answer:#}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn a_private_declaration_is_not_served() -> TestResult {
    let workspace = served_dependent_workspace().await?;
    let (_directory, client, server_task) = workspace.served;
    helper_indexed(&client).await?;

    let answer = get_symbol(
        &client,
        json!({ "name": "helper_private", "scope": "dependencies" }),
    )
    .await?;
    assert_eq!(answer["hits"], json!([]), "{answer:#}");
    assert_eq!(answer["pagination"]["total_pages"], json!(0), "{answer:#}");

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn the_project_scope_leaves_the_package_out() -> TestResult {
    let workspace = served_dependent_workspace().await?;
    let (_directory, client, server_task) = workspace.served;
    helper_indexed(&client).await?;

    for arguments in [
        json!({ "name": "helper_beacon" }),
        json!({ "name": "helper_beacon", "scope": "project" }),
    ] {
        let answer = get_symbol(&client, arguments.clone()).await?;
        assert_eq!(answer["hits"], json!([]), "{arguments} {answer:#}");
        assert!(
            answer.get("warnings").is_none(),
            "a dependency warning rides only an answer whose scope reaches dependencies: \
             {arguments} {answer:#}"
        );
    }

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn the_all_scope_lists_the_project_hit_before_the_package_hit() -> TestResult {
    let workspace = served_dependent_workspace().await?;
    let (_directory, client, server_task) = workspace.served;
    helper_indexed(&client).await?;

    let answer = get_symbol(
        &client,
        json!({ "name": "beacon", "scope": "all", "limit": 10 }),
    )
    .await?;
    let hits = answer["hits"].as_array().ok_or("hits are an array")?;
    assert!(hits.len() >= 2, "{answer:#}");
    for hit in hits {
        assert_one_location(hit);
    }
    assert_eq!(hits[0]["path"], json!("src/lib.rs"), "{answer:#}");
    assert_eq!(hits[0]["symbol"]["name"], json!("beacon"), "{answer:#}");
    assert_eq!(hits[1]["unit"], json!(HELPER_UNIT), "{answer:#}");
    assert_eq!(hits[1]["symbol"]["name"], json!("beacon"), "{answer:#}");

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn a_dependency_scoped_search_answers_the_package_declaration_by_unit() -> TestResult {
    let workspace = served_dependent_workspace().await?;
    let (_directory, client, server_task) = workspace.served;
    helper_indexed(&client).await?;

    let answer = search(
        &client,
        json!({ "query": "helper_beacon", "scope": "dependencies" }),
    )
    .await?;

    let results = answer["results"].as_array().ok_or("results are an array")?;
    assert_eq!(results.len(), 1, "{answer:#}");
    let hit = &results[0];
    assert_one_location(hit);
    assert_eq!(hit["unit"], json!(HELPER_UNIT), "{hit:#}");
    assert_eq!(hit["matched_by"], json!(["name"]), "{hit:#}");
    assert_eq!(hit["hit"]["target"], json!("symbol"), "{hit:#}");
    assert_eq!(
        hit["hit"]["symbol"]["name"],
        json!("helper_beacon"),
        "{hit:#}"
    );
    assert_eq!(
        hit["hit"]["symbol"]["origin"]["location"],
        json!("dependency"),
        "{hit:#}"
    );
    assert_eq!(hit["line"], json!(1), "{hit:#}");
    assert!(
        hit.get("source").is_none() && hit.get("score").is_none(),
        "an omitted include attaches neither excerpt nor score: {hit:#}"
    );
    assert!(
        hit.get("traversal_path").is_none() && hit.get("distance").is_none(),
        "a lexical hit carries no walk: {hit:#}"
    );
    assert!(
        answer["warnings"]
            .as_array()
            .into_iter()
            .flatten()
            .all(|warning| warning["package"]["name"] != json!("helper")),
        "an indexed package is never reported skipped: {answer:#}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn the_all_scope_search_answers_project_and_package_hits() -> TestResult {
    let workspace = served_dependent_workspace().await?;
    let (_directory, client, server_task) = workspace.served;
    helper_indexed(&client).await?;

    let answer = search(
        &client,
        json!({
            "query": "beacon",
            "scope": "all",
            "target": "symbol",
            "include": ["source"],
            "limit": 10
        }),
    )
    .await?;

    let located = located_names(&answer);
    for expected in [
        ("beacon".to_owned(), false),
        ("beacon".to_owned(), true),
        ("helper_beacon".to_owned(), true),
    ] {
        assert!(located.contains(&expected), "{expected:?} {answer:#}");
    }
    let results = answer["results"].as_array().ok_or("results are an array")?;
    for hit in results {
        assert_one_location(hit);
        assert!(hit["source"].is_string(), "{hit:#}");
    }
    let project = results
        .iter()
        .find(|hit| hit.get("path").is_some())
        .ok_or("the project hit is addressed by path")?;
    assert_eq!(project["path"], json!("src/lib.rs"), "{project:#}");

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn a_dependency_scoped_search_with_traversal_refuses_invalid_request() -> TestResult {
    let workspace = served_dependent_workspace().await?;
    let (_directory, client, server_task) = workspace.served;
    search(&client, json!({ "query": "beacon" })).await?;

    let wire = refused_search(
        &client,
        json!({
            "query": "beacon",
            "scope": "dependencies",
            "traversal": { "seed": "rift://symbol/rust/src/lib.rs/beacon" }
        }),
    )
    .await?;

    assert_eq!(wire["code"], json!("invalid_request"), "{wire:#}");
    assert!(
        wire["message"]
            .as_str()
            .is_some_and(|message| message.contains("traversal")),
        "the refusal names the field: {wire:#}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn a_revision_search_with_a_dependency_scope_refuses_invalid_request() -> TestResult {
    let workspace = served_dependent_workspace().await?;
    let (directory, client, server_task) = workspace.served;
    // A committed baseline, so `main` resolves and the scope rule is what refuses; the
    // workspace database stays out of the commit.
    fs::write(directory.path().join(".gitignore"), ".rift/\n")?;
    rift_history::fixture::init(directory.path());
    rift_history::fixture::commit_all(directory.path(), "fixture baseline");
    search(&client, json!({ "query": "beacon" })).await?;

    let wire = refused_search(
        &client,
        json!({ "query": "beacon", "scope": "all", "rev": "main" }),
    )
    .await?;

    assert_eq!(wire["code"], json!("invalid_request"), "{wire:#}");
    assert!(
        wire["message"]
            .as_str()
            .is_some_and(|message| message.contains("scope")),
        "the refusal names the field: {wire:#}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}
