//! `rift://map` end to end: the workspace orientation snapshot an agent reads to get its
//! bearings.
//!
//! The server routes a resource read by its URI family, so a suite that called the map
//! handler directly would leave that routing unproven. This one drives a live rmcp client,
//! the way an agent does.

mod hermetic_search;
// `workspace_client` carries the shared served-workspace scaffolding; this binary reads
// resources rather than calling tools, so it uses one entry point.
#[allow(dead_code)]
mod workspace_client;

use rmcp::model::{ReadResourceRequestParams, ResourceContents};
use serde_json::Value;
use workspace_client::{TestResult, served_workspace};

/// Reads one resource URI through the client and returns its text body.
async fn resource_body(
    client: &rmcp::service::RunningService<rmcp::RoleClient, ()>,
    uri: &str,
) -> TestResult<Value> {
    let answer = client
        .read_resource(ReadResourceRequestParams::new(uri.to_owned()))
        .await?;
    let ResourceContents::TextResourceContents { text, .. } = answer
        .contents
        .first()
        .ok_or("a resource read answers with one content")?
    else {
        return Err("a map read answers with text".into());
    };
    Ok(serde_json::from_str(text)?)
}

#[tokio::test]
async fn the_map_resource_answers_revision_languages_modules_and_entry_points() -> TestResult {
    let (_directory, client, server_task) = served_workspace(
        &[
            (
                "src/lib.rs",
                "pub fn beacon() {}\nfn main() { beacon(); }\n",
            ),
            ("docs/guide.md", "# Guide\n"),
        ],
        None,
    )
    .await?;

    let body = resource_body(&client, "rift://map").await?;

    assert_eq!(body["revision"].as_str().map(str::len), Some(8), "{body:#}");

    let languages = body["languages"]
        .as_array()
        .ok_or("map languages are an array")?;
    let rust = languages
        .iter()
        .find(|language| language["language"] == "rust")
        .ok_or("the rust entry is reported")?;
    assert_eq!(rust["files"], Value::from(1), "{rust}");
    assert_eq!(rust["symbols"], Value::from(2), "{rust}");

    let modules = body["modules"]
        .as_array()
        .ok_or("map modules are an array")?;
    let src = modules
        .iter()
        .find(|module| module["path"] == "src")
        .ok_or("the src module is reported")?;
    assert_eq!(src["files"], Value::from(1), "{src}");
    assert_eq!(src["symbols"], Value::from(2), "{src}");
    assert!(
        modules.iter().all(|module| module["path"] != "src/lib.rs"),
        "modules name directories, not files: {body:#}"
    );

    assert_eq!(
        body["entry_points"],
        serde_json::json!(["rift://symbol/rust/src/lib.rs/main"]),
        "{body:#}"
    );
    assert_eq!(
        body["docs"],
        serde_json::json!(["docs/guide.md"]),
        "{body:#}"
    );
    assert_eq!(body["pagination"]["page_index"], Value::from(0));
    assert_eq!(body["pagination"]["total_pages"], Value::from(1));

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn an_unknown_query_string_on_the_map_uri_is_refused() -> TestResult {
    let (_directory, client, server_task) =
        served_workspace(&[("lib.rs", "pub fn beacon() {}\n")], None).await?;

    let error = client
        .read_resource(ReadResourceRequestParams::new(
            "rift://map?page_index=0".to_owned(),
        ))
        .await
        .expect_err("a query string on rift://map names no resource");
    assert!(
        error.to_string().contains("rift://map?page_index=0"),
        "{error}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

#[tokio::test]
async fn declared_resources_lists_map() -> TestResult {
    let (_directory, client, server_task) =
        served_workspace(&[("lib.rs", "pub fn beacon() {}\n")], None).await?;

    let resources = client.list_all_resources().await?;
    assert!(
        resources
            .iter()
            .any(|resource| resource.uri == "rift://map"),
        "{resources:#?}"
    );

    client.cancel().await?;
    server_task.await?;
    Ok(())
}

/// A dependency-free lockfile beside a manifest declaring `serde`: what `cargo metadata
/// --locked --offline` answers from when the registry cache holds serde, and what the
/// static fallback reads when it does not. Either path lists the same package.
const LOCK_WITH_SERDE: &str = "\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = \"probe\"
version = \"0.1.0\"
dependencies = [
 \"serde\",
]

[[package]]
name = \"serde\"
version = \"1.0.228\"
source = \"registry+https://github.com/rust-lang/crates.io-index\"
checksum = \"9a8e94ea7f378bd32cbbd37198a4a91436180c5bb472411e48b5ec2e2124ae9e\"
";

/// The same lockfile after a second direct dependency was pinned. The manifest still names
/// only `serde`, so `--locked` refuses and the static path lists both.
const LOCK_WITH_SERDE_AND_ITOA: &str = "\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = \"itoa\"
version = \"1.0.15\"
source = \"registry+https://github.com/rust-lang/crates.io-index\"
checksum = \"4a5f13b858c8d314ee3e8f639011f7ccefe71f97f96e50151fb991f267928e2c\"

[[package]]
name = \"probe\"
version = \"0.1.0\"
dependencies = [
 \"itoa\",
 \"serde\",
]

[[package]]
name = \"serde\"
version = \"1.0.228\"
source = \"registry+https://github.com/rust-lang/crates.io-index\"
checksum = \"9a8e94ea7f378bd32cbbd37198a4a91436180c5bb472411e48b5ec2e2124ae9e\"
";

/// `packages` lists the direct dependencies the Cargo resolver cataloged, and follows the
/// lockfile: rewriting `Cargo.lock` under the server re-catalogs on the next publication,
/// which the tool call after the write waits for.
#[tokio::test]
async fn the_map_lists_direct_packages_and_follows_the_lockfile() -> TestResult {
    let (directory, client, server_task) = served_workspace(
        &[
            (
                "Cargo.toml",
                "[package]\nname = \"probe\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n\
                 [dependencies]\nserde = \"1.0.228\"\n",
            ),
            ("Cargo.lock", LOCK_WITH_SERDE),
            ("src/lib.rs", "pub fn beacon() {}\n"),
        ],
        None,
    )
    .await?;

    let body = resource_body(&client, "rift://map").await?;
    assert_eq!(
        body["packages"],
        serde_json::json!([{ "manager": "cargo", "name": "serde", "version": "1.0.228" }]),
        "{body:#}"
    );

    std::fs::write(
        directory.path().join("Cargo.lock"),
        LOCK_WITH_SERDE_AND_ITOA,
    )?;
    // A tool call captures the tree and waits for the publication that indexes it; the
    // map is computed for that same publication.
    let request =
        workspace_client::tool_request("get_symbol", &serde_json::json!({ "name": "beacon" }));
    client.call_tool(request).await?;

    let body = resource_body(&client, "rift://map").await?;
    let names: Vec<&str> = body["packages"]
        .as_array()
        .ok_or("map packages are an array")?
        .iter()
        .filter_map(|package| package["name"].as_str())
        .collect();
    assert_eq!(names, ["itoa", "serde"], "{body:#}");

    client.cancel().await?;
    server_task.abort();
    Ok(())
}
