[package]
name = "rift-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Syntax fact extraction for Rift"

[lints]
workspace = true

[dependencies]
rift-core.workspace = true
rift-protocol.workspace = true
serde.workspace = true
rift-provider.workspace = true
tree-sitter.workspace = true
tree-sitter-javascript.workspace = true
tree-sitter-json.workspace = true
tree-sitter-md.workspace = true
tree-sitter-rust.workspace = true
tree-sitter-typescript.workspace = true
tree-sitter-yaml.workspace = true
