#[doc(hidden)]
pub const REGISTRY_NAMESPACE: &str = "rift";
#[doc(hidden)]
pub const REGISTERED_SLUGS: &[&str] = &[
    "rift.analysis.context7_entry_invalid",
    "rift.analysis.context7_malformed",
    "rift.analysis.context7_oversized",
    "rift.analysis.context7_too_many_entries",
    "rift.analysis.documentation_digest_mismatch",
    "rift.analysis.documentation_duplicate_source",
    "rift.analysis.documentation_encoding_failed",
    "rift.analysis.documentation_format_invalid",
    "rift.analysis.documentation_identity_invalid",
    "rift.analysis.documentation_limit_exceeded",
    "rift.analysis.documentation_notebook_invalid",
    "rift.analysis.documentation_order_invalid",
    "rift.analysis.documentation_origin_invalid",
    "rift.analysis.documentation_range_invalid",
    "rift.analysis.documentation_revision_invalid",
    "rift.analysis.documentation_target_missing",
    "rift.analysis.package_declarations_exceeded",
    "rift.analysis.package_identity_invalid",
    "rift.analysis.package_input_duplicate_path",
    "rift.analysis.package_input_identity_invalid",
    "rift.analysis.package_input_origin_invalid",
    "rift.analysis.package_input_too_many_bytes",
    "rift.analysis.package_input_too_many_files",
    "rift.analysis.package_provider_failed",
    "rift.analysis.package_retained_source_bytes_exceeded",
    "rift.analysis.package_retained_source_limits_invalid",
    "rift.analysis.package_syntax_unavailable",
    "rift.analysis.source_pattern_invalid",
    "rift.cli.install_home_unresolved",
    "rift.cli.install_remove_failed",
    "rift.cli.install_settings_unparsable",
    "rift.cli.install_template_missing_tool",
    "rift.cli.install_write_failed",
    "rift.cli.server_already_serving",
    "rift.cli.server_election_unreleased",
    "rift.cli.server_logs_unavailable",
    "rift.cli.server_spawn_failed",
    "rift.cli.server_start_exited",
    "rift.cli.server_start_timed_out",
    "rift.cli.server_stop_refused",
    "rift.cli.server_stop_request_failed",
    "rift.cli.server_stop_timed_out",
    "rift.cli.update_archive_contents_invalid",
    "rift.cli.update_archive_extraction_failed",
    "rift.cli.update_archive_file_inspection_failed",
    "rift.cli.update_archive_file_not_regular",
    "rift.cli.update_archive_file_size_invalid",
    "rift.cli.update_archive_member_too_large",
    "rift.cli.update_binary_invalid",
    "rift.cli.update_checksum_manifest_invalid",
    "rift.cli.update_checksum_mismatch",
    "rift.cli.update_checksum_read_failed",
    "rift.cli.update_download_failed",
    "rift.cli.update_download_too_large",
    "rift.cli.update_prerelease_unsupported",
    "rift.cli.update_publish_copy_failed",
    "rift.cli.update_publish_failed",
    "rift.cli.update_publish_parent_missing",
    "rift.cli.update_publish_pending_cleanup",
    "rift.cli.update_release_file_inspection_failed",
    "rift.cli.update_release_file_not_regular",
    "rift.cli.update_release_file_size_invalid",
    "rift.cli.update_release_metadata_invalid",
    "rift.cli.update_release_tag_invalid",
    "rift.cli.update_rollback_cleanup_failed",
    "rift.cli.update_rollback_failed",
    "rift.cli.update_staging_failed",
    "rift.cli.update_version_invalid",
    "rift.core.configuration_command_argument_oversized",
    "rift.core.configuration_command_program_absolute",
    "rift.core.configuration_command_program_dot_segment",
    "rift.core.configuration_command_program_empty",
    "rift.core.configuration_command_program_oversized",
    "rift.core.configuration_command_program_whitespace",
    "rift.core.configuration_embedding_endpoint_invalid",
    "rift.core.configuration_embedding_identifier_invalid",
    "rift.core.configuration_embedding_model_invalid",
    "rift.core.configuration_file_name_invalid",
    "rift.core.configuration_history_cpu_share_invalid",
    "rift.core.configuration_history_release_pattern_invalid",
    "rift.core.configuration_history_releases_missing",
    "rift.core.configuration_history_releases_outside_selective",
    "rift.core.configuration_invalid",
    "rift.core.configuration_is_directory",
    "rift.core.configuration_language_identity_invalid",
    "rift.core.configuration_language_include_duplicate",
    "rift.core.configuration_language_lsp_unknown",
    "rift.core.configuration_limit_out_of_range",
    "rift.core.configuration_log_capture_invalid",
    "rift.core.configuration_lsp_embedded_extras",
    "rift.core.configuration_lsp_engine_missing",
    "rift.core.configuration_lsp_engine_selection_conflict",
    "rift.core.configuration_lsp_environment_key_invalid",
    "rift.core.configuration_lsp_initialization_options_not_object",
    "rift.core.configuration_lsp_name_invalid",
    "rift.core.configuration_malformed",
    "rift.core.configuration_oversized",
    "rift.core.configuration_package_selector_invalid",
    "rift.core.configuration_path_pattern_invalid",
    "rift.core.configuration_port_range_inverted",
    "rift.core.configuration_port_selection_conflict",
    "rift.core.configuration_search_weights_invalid",
    "rift.core.configuration_unit_parse",
    "rift.core.configuration_unreadable",
    "rift.core.configuration_variable_malformed",
    "rift.core.configuration_variable_not_unicode",
    "rift.core.configuration_variable_unknown",
    "rift.core.contribution_duplicate_fact",
    "rift.core.contribution_invalid_kind",
    "rift.core.contribution_invalid_language",
    "rift.core.contribution_invalid_name",
    "rift.core.contribution_invalid_namespace",
    "rift.core.contribution_invalid_namespace_version",
    "rift.core.contribution_invalid_origin",
    "rift.core.contribution_invalid_record",
    "rift.core.contribution_invalid_reference",
    "rift.core.contribution_invalid_source_range",
    "rift.core.contribution_too_many_facts",
    "rift.core.contribution_too_many_namespaced_facts",
    "rift.core.contribution_too_much_evidence",
    "rift.core.contribution_unbound_identity",
    "rift.core.identity_invalid",
    "rift.core.path_absolute",
    "rift.core.path_backslash",
    "rift.core.path_control_character",
    "rift.core.path_dot_segment",
    "rift.core.path_empty",
    "rift.core.path_empty_segment",
    "rift.core.path_non_canonical_unicode",
    "rift.core.path_rift_state",
    "rift.core.path_too_long",
    "rift.core.resolver_id_empty",
    "rift.core.resolver_id_invalid_character",
    "rift.core.resolver_id_too_long",
    "rift.core.revision_zero",
    "rift.core.source_unit_id_invalid_address",
    "rift.core.source_unit_id_invalid_encoding",
    "rift.core.source_unit_id_invalid_key",
    "rift.core.source_unit_id_invalid_resolver",
    "rift.core.source_unit_id_non_canonical",
    "rift.core.source_unit_id_too_long",
    "rift.history.blob_too_large",
    "rift.history.contribution_invalid",
    "rift.history.path_unrepresentable",
    "rift.history.revision_not_commit",
    "rift.history.revision_unknown",
    "rift.history.storage",
    "rift.history.too_many_tags",
    "rift.history.tree_too_large",
    "rift.history.unversioned",
    "rift.history_store.database",
    "rift.history_store.folder",
    "rift.history_store.lock_unstable",
    "rift.index.database_failed",
    "rift.index.lexical_document_location_unsupported",
    "rift.index.lexical_duplicate_identity",
    "rift.index.lexical_record_limit",
    "rift.index.lexical_storage",
    "rift.index.lexical_stored_kind_invalid",
    "rift.index.lexical_stored_path_invalid",
    "rift.index.lexical_unit_limit",
    "rift.index.lexical_unit_too_large",
    "rift.index.workspace_cancelled",
    "rift.index.workspace_changed_during_capture",
    "rift.index.workspace_composition",
    "rift.index.workspace_documentation_limit",
    "rift.index.workspace_file_too_large",
    "rift.index.workspace_filesystem",
    "rift.index.workspace_history",
    "rift.index.workspace_invalid_path",
    "rift.index.workspace_invalid_root",
    "rift.index.workspace_invalid_source",
    "rift.index.workspace_language_include_required",
    "rift.index.workspace_language_match_conflict",
    "rift.index.workspace_provider",
    "rift.index.workspace_result_limit",
    "rift.index.workspace_syntax",
    "rift.index.workspace_too_deep",
    "rift.index.workspace_too_many_files",
    "rift.index.workspace_workspace_too_large",
    "rift.index.workspace_zero_limit",
    "rift.lsp.capabilities_position_encoding_unsupported",
    "rift.lsp.correlation_pending_requests_exceeded",
    "rift.lsp.correlation_response_unknown",
    "rift.lsp.engine_analyzing",
    "rift.lsp.engine_capability_absent",
    "rift.lsp.engine_connection_closed",
    "rift.lsp.engine_ended",
    "rift.lsp.engine_launch_failed",
    "rift.lsp.engine_message_unreadable",
    "rift.lsp.engine_program_absolute",
    "rift.lsp.engine_program_empty",
    "rift.lsp.engine_refused_retryable",
    "rift.lsp.engine_refused_terminal",
    "rift.lsp.engine_result_invalid",
    "rift.lsp.engine_timed_out",
    "rift.lsp.framing_content_length_invalid",
    "rift.lsp.framing_content_length_missing",
    "rift.lsp.framing_header_malformed",
    "rift.lsp.framing_header_too_long",
    "rift.lsp.framing_message_too_long",
    "rift.lsp.position_character_misaligned",
    "rift.lsp.position_character_out_of_range",
    "rift.lsp.position_line_out_of_range",
    "rift.lsp.position_offset_inside_line_ending",
    "rift.lsp.position_offset_misaligned",
    "rift.lsp.position_offset_out_of_range",
    "rift.lsp.uri_host_refused",
    "rift.lsp.uri_outside_root",
    "rift.lsp.uri_path_not_decodable",
    "rift.lsp.uri_root_not_absolute",
    "rift.lsp.uri_root_not_unicode",
    "rift.lsp.uri_scheme_refused",
    "rift.lsp.uri_uri_malformed",
    "rift.mcp.answer_structure_failed",
    "rift.mcp.answer_text_failed",
    "rift.mcp.answer_text_limit",
    "rift.mcp.arguments_not_object",
    "rift.mcp.election_already_serving",
    "rift.mcp.election_document_invalid",
    "rift.mcp.election_storage_failed",
    "rift.mcp.forward_unanswered",
    "rift.mcp.http_ports_exhausted",
    "rift.mcp.http_serve_failed",
    "rift.mcp.parameter_invalid",
    "rift.mcp.project_hit_identity_missing",
    "rift.mcp.project_hit_identity_refused",
    "rift.mcp.project_hit_identity_undecodable",
    "rift.mcp.project_hit_name_unmatched",
    "rift.mcp.project_hit_unit_invalid",
    "rift.mcp.proxy_identity_failed",
    "rift.mcp.proxy_initialization_failed",
    "rift.mcp.proxy_task_failed",
    "rift.mcp.proxy_unexpected_quit",
    "rift.mcp.spawn_failed",
    "rift.mcp.spawn_no_output",
    "rift.mcp.start_building",
    "rift.provider.cache_too_many_keys",
    "rift.provider.composition_dangling_input",
    "rift.provider.composition_duplicate_stage",
    "rift.provider.composition_foreign_flow",
    "rift.provider.composition_invalid_name",
    "rift.provider.composition_missing_output",
    "rift.provider.composition_stage_not_found",
    "rift.provider.composition_type_mismatch",
    "rift.provider.publication_contribution_limit",
    "rift.provider.publication_duplicate_symbol",
    "rift.provider.publication_provider_contribution_limit",
    "rift.provider.publication_provider_limit",
    "rift.provider.publication_provider_mismatch",
    "rift.provider.publication_revision_mismatch",
    "rift.provider.publication_zero_limit",
    "rift.ranking.capabilities_incompatible",
    "rift.ranking.document_field_length",
    "rift.ranking.document_identity_empty",
    "rift.ranking.fusion_constant_invalid",
    "rift.ranking.pattern_size",
    "rift.ranking.pattern_syntax",
    "rift.ranking.query_empty",
    "rift.ranking.query_length",
    "rift.ranking.query_phrase_limit",
    "rift.ranking.query_quote_unterminated",
    "rift.ranking.query_term_length",
    "rift.ranking.ranking_weights_invalid",
    "rift.ranking.reader_failed",
    "rift.search.encode_failed",
    "rift.search.model_cache_unavailable",
    "rift.search.model_configuration_invalid",
    "rift.search.model_download_failed",
    "rift.search.model_download_too_large",
    "rift.search.model_file_missing",
    "rift.search.model_source_invalid",
    "rift.search.task_failed",
    "rift.search.text_limit",
    "rift.search.tokenizer_unreadable",
    "rift.search.vector_coordinate_invalid",
    "rift.search.vector_width_mismatch",
    "rift.search.weights_unreadable",
    "rift.server.read_cancelled",
    "rift.server.read_capacity_timeout",
    "rift.server.read_engine_answer",
    "rift.server.read_invalid",
    "rift.server.read_not_found",
    "rift.server.read_source_unavailable",
    "rift.server.read_storage",
    "rift.server.read_symbol_alternatives_unavailable",
    "rift.server.read_task",
    "rift.server.read_unavailable",
    "rift.server.read_unclaimed_extension",
    "rift.server.read_unsupported",
    "rift.syntax.facts_count_exceeded",
    "rift.syntax.facts_depth_exceeded",
    "rift.syntax.facts_kind_invalid",
    "rift.syntax.facts_name_invalid",
    "rift.syntax.facts_order_invalid",
    "rift.syntax.facts_range_invalid",
    "rift.syntax.facts_reference_invalid",
    "rift.syntax.facts_source_mismatch",
    "rift.syntax.facts_source_too_large",
    "rift.syntax.facts_structure_invalid",
    "rift.syntax.facts_text_exceeded",
    "rift.syntax.incompatible_grammar",
    "rift.syntax.invalid_markdown_ranges",
    "rift.syntax.invalid_query",
    "rift.syntax.markdown_progress_exceeded",
    "rift.syntax.parse_cancelled",
    "rift.syntax.position_overflow",
    "rift.syntax.source_too_large",
    "rift.syntax.too_deep",
    "rift.syntax.too_many_captures",
    "rift.syntax.too_many_markdown_inline_ranges",
    "rift.syntax.too_many_nodes",
    "rift.syntax.unknown_node_kind",
    "rift.syntax.zero_limit",
    "rift.tracing.log_batch_limit",
    "rift.tracing.log_queue_limit",
    "rift.tracing.log_store_failed",
    "rift.tracing.log_stream_unavailable",
    "rift.tracing.log_subscription_limit",
];

/// Registered errors under `rift.analysis`.
pub mod analysis;

/// Registered errors under `rift.cli`.
pub mod cli;

/// Registered errors under `rift.core`.
pub mod core;

/// Registered errors under `rift.history`.
pub mod history;

/// Registered errors under `rift.history_store`.
pub mod history_store;

/// Registered errors under `rift.index`.
pub mod index;

/// Registered errors under `rift.lsp`.
pub mod lsp;

/// Registered errors under `rift.mcp`.
pub mod mcp;

/// Registered errors under `rift.provider`.
pub mod provider;

/// Registered errors under `rift.ranking`.
pub mod ranking;

/// Registered errors under `rift.search`.
pub mod search;

/// Registered errors under `rift.server`.
pub mod server;

/// Registered errors under `rift.syntax`.
pub mod syntax;

/// Registered errors under `rift.tracing`.
pub mod tracing;
