[package]
name = "rift-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Workspace application service for Rift"

[lints]
workspace = true

[dependencies]
rift-core.workspace = true
rift-index.workspace = true
rift-protocol.workspace = true
rift-provider.workspace = true
