import "@/app/global.css";
import { RootProvider } from "fumadocs-ui/provider";
import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import { cn } from "@/lib/utils";

// Two families, per the design system: Geist Mono for display, section
// labels and code; Inter 300 for lead and body copy.
const geistMono = Geist_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-geist-mono",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-inter",
});

const TITLE = "rift — agentic development toolkit";
const DESCRIPTION = "Agentic development toolkit for reading, discovering and editing codebases.";

// Next does not apply next.config `basePath` to metadata URLs, so every one of
// them has to be prefixed by hand or it 404s under /rift.
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

// public/og.png, generated by `bun run og`.
const CARD = { url: `${BASE_PATH}/og.png`, width: 1280, height: 640, alt: TITLE };

export const metadata: Metadata = {
  // Scrapers need absolute URLs; this is what the relative ones resolve against.
  metadataBase: new URL("https://volar.sh"),
  title: { default: TITLE, template: "%s — rift" },
  description: DESCRIPTION,
  icons: { icon: `${BASE_PATH}/logo.svg` },
  openGraph: {
    type: "website",
    siteName: "rift",
    url: `${BASE_PATH}/`,
    title: TITLE,
    description: DESCRIPTION,
    images: [CARD],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    images: [CARD],
  },
};

export default function Layout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cn(inter.variable, geistMono.variable)} suppressHydrationWarning>
      <body className="flex flex-col min-h-screen">
        {/*
          `type: "static"` because `output: "export"` has no server to answer a
          search request: app/api/search pre-renders the Orama index to a file
          and the client downloads it once and queries it in the browser.
          `api` is the download URL, and it needs the basePath spelled out —
          it defaults to a bare "/api/search", which 404s under /rift.
        */}
        <RootProvider
          search={{
            options: {
              type: "static",
              api: `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}/api/search`,
            },
          }}
        >
          {children}
        </RootProvider>
      </body>
    </html>
  );
}
