#![allow(clippy::default_trait_access)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::struct_field_names)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
#![allow(dead_code)]
//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Rift Global Package API
//! Source: docs/public/global-api.openapi.json
//! Version: 0.0.43
//! Generated by `oas3-gen v0.28.0`
//!
//! REST contract for package capabilities, resolution, declaration search, and symbol reads.

use serde::{Deserialize, Serialize};
use validator::Validate;
/// One package as its package manager identifies it.
#[derive(
    Debug,
    Clone,
    PartialEq,
    Serialize,
    Deserialize,
    validator::Validate,
    oas3_gen_support::Default
)]
#[serde(deny_unknown_fields)]
pub struct PackageIdentity {
    /// Package manager or ecosystem name.
    #[validate(length(max = 128u64))]
    pub manager: String,
    /// Package name in that ecosystem.
    #[validate(length(max = 4_096u64))]
    pub name: String,
    /// Resolved package version.
    #[validate(length(max = 4_096u64))]
    pub version: String,
}
/// Stable identity of one source unit in the source catalog: a resolver identity, then that
/// resolver's canonical unit key in canonical percent-encoding - for the project resolver, the
/// project-relative path, as `rift://source/project/src/lib.rs`. An identity derives from its
/// resolver's canonical human-readable key; digests appear on the wire only as short witnesses
/// where byte-identity is required.
pub type SourceUnitId = String;
/// Identity of one symbol. The name after the language is the provider's stable qualified
/// name for the declaration; where the language derives module identity from the file path,
/// as TypeScript does, that path is part of the name. A `~N` suffix separates declarations
/// the qualified name alone cannot, such as overloads that dispatch separately. A move can
/// change the identity when the language includes module path in that qualified name.
pub type SymbolId = String;
/// Readable Symbol assembled from normalized Contributions. Source structure lives in Node
/// and is connected through Relationship.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct Symbol {
    /// The symbol this one belongs to - the class that owns a method, the module that owns
    /// a function. Ownership is not lexical: a Go method sits beside its type and a Rust
    /// method inside an `impl` block, both naming the type here; absent at the top level.
    pub container: Option<SymbolId>,
    /// Whether language semantics confine this symbol to the document that declares it. The
    /// provider classifies locality from its language model; absent when `false`.
    #[default(Some(false))]
    pub document_local: Option<bool>,
    /// Doc comments attached to the declaration, with the markup format they were written
    /// in. Absent when empty.
    #[default(Some(Default::default()))]
    pub documentation: Option<Vec<Documentation>>,
    /// Facts a provider carries that the model has no field for, under a reverse-domain key.
    /// Keys and values use RFC 8785 canonical JSON. Consumers skip entries they do not
    /// implement.
    pub extensions: Option<serde_json::Value>,
    /// Portable classification for cross-language queries, absent when empty. The local
    /// kinds `trait` and `interface` can both carry the `type` facet.
    #[default(Some(Default::default()))]
    pub facets: Option<Vec<SymbolFacet>>,
    /// Unique identifier of this Symbol across the whole workspace. Absent for an
    /// unestablished symbol: no accepted evidence, or more than one, established its
    /// identity.
    pub id: Option<SymbolId>,
    /// A provider-local kind preserving the construct name used by that language implementation.
    pub kind: String,
    /// A language name and its optional dialect, joined by `:`. `sql` and `sql:postgresql` are two languages with two symbol spaces.
    pub language: String,
    /// Language keywords qualifying the declaration: `export`, `async`, `const`. Absent
    /// when empty.
    #[default(Some(Default::default()))]
    pub modifiers: Option<Vec<String>>,
    /// The human-readable name, as written in the source: `parseConfig`. Rendered
    /// signatures live in `signatures`.
    pub name: String,
    /// Where a symbol belongs and how its declaration came to exist. Source location and
    /// generation are separate: generated code can belong to the project or to a dependency.
    /// Absent from `Symbol` entirely when it says a project declaration, authored, with no
    /// package.
    pub origin: Option<SymbolOrigin>,
    /// One entry per callable form, absent when empty. Where the language dispatches
    /// overloads separately they are separate symbols joined by the `overloads` edge;
    /// several entries here are alternative forms of one dispatch target, as
    /// `typing.overload` writes them.
    #[default(Some(Default::default()))]
    pub signatures: Option<Vec<Signature>>,
    /// The types this symbol carries, each tagged with the role it plays: a return type, a
    /// field type, a bound. Absent when empty.
    #[default(Some(Default::default()))]
    pub types: Option<Vec<TypeBinding>>,
    /// How widely the symbol is visible, in the language's own terms - `public`, `private`,
    /// `pub(crate)`. Absent where the language has no such concept.
    pub visibility: Option<String>,
}
/// Where a symbol belongs and how its declaration came to exist. Source location and
/// generation are separate: generated code can belong to the project or to a dependency.
/// Absent from `Symbol` entirely when it says a project declaration, authored, with no
/// package.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct SymbolOrigin {
    /// Which of the four places the declaration belongs. Absent exactly when
    /// `source_kind` is `synthetic`.
    pub location: Option<SourceLocationKind>,
    /// The package that owns the declaration: present for `dependency`, and optionally
    /// for `project`. Absent for `stdlib`, `external`, and a synthetic declaration.
    pub package: Option<PackageIdentity>,
    /// How source or a declaration came to exist.
    pub source_kind: SourceKind,
}
/// How source or a declaration came to exist.
#[derive(Debug, Clone, PartialEq, Eq, Hash, oas3_gen_support::Default)]
pub enum SourceKind {
    /// A person wrote it.
    #[default]
    Authored,
    /// A tool produced it from other source.
    Generated,
    /// The provider minted it without any source text.
    Synthetic,
}
impl core::fmt::Display for SourceKind {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Authored => write!(f, "authored"),
            Self::Generated => write!(f, "generated"),
            Self::Synthetic => write!(f, "synthetic"),
        }
    }
}
impl<'de> serde::Deserialize<'de> for SourceKind {
    fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_ascii_lowercase().as_str() {
            "authored" => Ok(SourceKind::Authored),
            "generated" => Ok(SourceKind::Generated),
            "synthetic" => Ok(SourceKind::Synthetic),
            _ => {
                Err(
                    serde::de::Error::unknown_variant(
                        &s,
                        &["authored", "generated", "synthetic"],
                    ),
                )
            }
        }
    }
}
/// Which of the four places a declaration's source belongs, on `SymbolOrigin`. Package
/// ownership is the separate `package` field: a `project` declaration can carry one too,
/// and `dependency` always does.
#[derive(Debug, Clone, PartialEq, Eq, Hash, oas3_gen_support::Default)]
pub enum SourceLocationKind {
    /// Owned by the current workspace.
    #[default]
    Project,
    /// Owned by one resolved dependency.
    Dependency,
    /// Installed with the language toolchain.
    Stdlib,
    /// Outside the project, dependency graph, and standard library.
    External,
}
impl core::fmt::Display for SourceLocationKind {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Project => write!(f, "project"),
            Self::Dependency => write!(f, "dependency"),
            Self::Stdlib => write!(f, "stdlib"),
            Self::External => write!(f, "external"),
        }
    }
}
impl<'de> serde::Deserialize<'de> for SourceLocationKind {
    fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_ascii_lowercase().as_str() {
            "project" => Ok(SourceLocationKind::Project),
            "dependency" => Ok(SourceLocationKind::Dependency),
            "stdlib" => Ok(SourceLocationKind::Stdlib),
            "external" => Ok(SourceLocationKind::External),
            _ => {
                Err(
                    serde::de::Error::unknown_variant(
                        &s,
                        &["project", "dependency", "stdlib", "external"],
                    ),
                )
            }
        }
    }
}
/// A language name and its optional dialect, joined by `:`. `sql` and `sql:postgresql` are two languages with two symbol spaces.
pub type Language = String;
/// One block of documentation attached to a declaration, in the markup it was written in.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct Documentation {
    /// Which markup the text is written in, since whoever displays a doc comment is the one that
    /// renders it.
    pub format: DocumentationFormat,
    /// The body of the comment, with the comment syntax stripped.
    pub text: String,
}
/// Which markup the text is written in, since whoever displays a doc comment is the one that
/// renders it.
#[derive(Debug, Clone, PartialEq, Eq, Hash, oas3_gen_support::Default)]
pub enum DocumentationFormat {
    /// Plain text with no markup to render.
    #[default]
    Plain,
    /// Markdown as authored in the source.
    Markdown,
}
impl core::fmt::Display for DocumentationFormat {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Plain => write!(f, "plain"),
            Self::Markdown => write!(f, "markdown"),
        }
    }
}
impl<'de> serde::Deserialize<'de> for DocumentationFormat {
    fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_ascii_lowercase().as_str() {
            "plain" => Ok(DocumentationFormat::Plain),
            "markdown" => Ok(DocumentationFormat::Markdown),
            _ => Err(serde::de::Error::unknown_variant(&s, &["plain", "markdown"])),
        }
    }
}
/// Facts a provider carries that the model has no field for, under a reverse-domain key.
/// Keys and values use RFC 8785 canonical JSON. Consumers skip entries they do not
/// implement.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(deny_unknown_fields)]
pub struct Extensions {}
/// One portable category a symbol falls into. Kinds are language-specific; facets are
/// shared, so a filter written once applies to every served language.
#[derive(Debug, Clone, PartialEq, Eq, Hash, oas3_gen_support::Default)]
pub enum SymbolFacet {
    /// A named scope that groups declarations.
    #[default]
    Namespace,
    /// A compilation or import unit.
    Module,
    /// Names a type.
    TypeType,
    /// Holds a runtime value.
    Value,
    /// Can be invoked.
    Callable,
    /// Belongs to a containing type.
    Member,
    /// Owns members of its own.
    MemberContainer,
    /// A declared input of a callable.
    Parameter,
    /// A generic parameter a declaration abstracts over.
    TypeParameter,
    /// Instances of it can be created.
    Constructible,
    /// Other types can inherit from it.
    Extensible,
    /// Other types can fulfil it.
    Implementable,
    /// Expands at compile time.
    Macro,
    /// Exercises other code as a test.
    Test,
    /// Decorates other declarations.
    Annotation,
    /// Adds members to a type declared elsewhere.
    Extension,
    /// One case of an enumeration.
    Variant,
    /// A closed set of variants.
    Enumeration,
    /// Another name for an existing symbol.
    Alias,
    /// A member accessed like a field but backed by code.
    Property,
    /// Declared without a complete implementation.
    Abstract,
    /// Creates instances of its container.
    Constructor,
    /// Belongs to the type rather than an instance.
    Static,
    /// Its value can change after initialization.
    Mutable,
    /// Visible outside its declaring scope.
    Public,
    /// Marked as discouraged for new use.
    Deprecated,
    /// Where execution starts.
    Entrypoint,
    /// Invoked through operator syntax.
    Operator,
    /// Runs asynchronously.
    Async,
    /// Yields a sequence of values over time.
    Generator,
}
impl core::fmt::Display for SymbolFacet {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Namespace => write!(f, "namespace"),
            Self::Module => write!(f, "module"),
            Self::TypeType => write!(f, "type"),
            Self::Value => write!(f, "value"),
            Self::Callable => write!(f, "callable"),
            Self::Member => write!(f, "member"),
            Self::MemberContainer => write!(f, "member_container"),
            Self::Parameter => write!(f, "parameter"),
            Self::TypeParameter => write!(f, "type_parameter"),
            Self::Constructible => write!(f, "constructible"),
            Self::Extensible => write!(f, "extensible"),
            Self::Implementable => write!(f, "implementable"),
            Self::Macro => write!(f, "macro"),
            Self::Test => write!(f, "test"),
            Self::Annotation => write!(f, "annotation"),
            Self::Extension => write!(f, "extension"),
            Self::Variant => write!(f, "variant"),
            Self::Enumeration => write!(f, "enumeration"),
            Self::Alias => write!(f, "alias"),
            Self::Property => write!(f, "property"),
            Self::Abstract => write!(f, "abstract"),
            Self::Constructor => write!(f, "constructor"),
            Self::Static => write!(f, "static"),
            Self::Mutable => write!(f, "mutable"),
            Self::Public => write!(f, "public"),
            Self::Deprecated => write!(f, "deprecated"),
            Self::Entrypoint => write!(f, "entrypoint"),
            Self::Operator => write!(f, "operator"),
            Self::Async => write!(f, "async"),
            Self::Generator => write!(f, "generator"),
        }
    }
}
impl<'de> serde::Deserialize<'de> for SymbolFacet {
    fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_ascii_lowercase().as_str() {
            "namespace" => Ok(SymbolFacet::Namespace),
            "module" => Ok(SymbolFacet::Module),
            "type" => Ok(SymbolFacet::TypeType),
            "value" => Ok(SymbolFacet::Value),
            "callable" => Ok(SymbolFacet::Callable),
            "member" => Ok(SymbolFacet::Member),
            "member_container" => Ok(SymbolFacet::MemberContainer),
            "parameter" => Ok(SymbolFacet::Parameter),
            "type_parameter" => Ok(SymbolFacet::TypeParameter),
            "constructible" => Ok(SymbolFacet::Constructible),
            "extensible" => Ok(SymbolFacet::Extensible),
            "implementable" => Ok(SymbolFacet::Implementable),
            "macro" => Ok(SymbolFacet::Macro),
            "test" => Ok(SymbolFacet::Test),
            "annotation" => Ok(SymbolFacet::Annotation),
            "extension" => Ok(SymbolFacet::Extension),
            "variant" => Ok(SymbolFacet::Variant),
            "enumeration" => Ok(SymbolFacet::Enumeration),
            "alias" => Ok(SymbolFacet::Alias),
            "property" => Ok(SymbolFacet::Property),
            "abstract" => Ok(SymbolFacet::Abstract),
            "constructor" => Ok(SymbolFacet::Constructor),
            "static" => Ok(SymbolFacet::Static),
            "mutable" => Ok(SymbolFacet::Mutable),
            "public" => Ok(SymbolFacet::Public),
            "deprecated" => Ok(SymbolFacet::Deprecated),
            "entrypoint" => Ok(SymbolFacet::Entrypoint),
            "operator" => Ok(SymbolFacet::Operator),
            "async" => Ok(SymbolFacet::Async),
            "generator" => Ok(SymbolFacet::Generator),
            _ => {
                Err(
                    serde::de::Error::unknown_variant(
                        &s,
                        &[
                            "namespace",
                            "module",
                            "type",
                            "value",
                            "callable",
                            "member",
                            "member_container",
                            "parameter",
                            "type_parameter",
                            "constructible",
                            "extensible",
                            "implementable",
                            "macro",
                            "test",
                            "annotation",
                            "extension",
                            "variant",
                            "enumeration",
                            "alias",
                            "property",
                            "abstract",
                            "constructor",
                            "static",
                            "mutable",
                            "public",
                            "deprecated",
                            "entrypoint",
                            "operator",
                            "async",
                            "generator",
                        ],
                    ),
                )
            }
        }
    }
}
/// A provider-local kind preserving the construct name used by that language implementation.
pub type ExactKind = String;
/// One callable form of a symbol: the text it renders as, the symbols that text points at,
/// and its structure. Overloads are separate entries.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct Signature {
    /// The signature as a reader sees it, in the language's own syntax.
    pub display: String,
    /// Effect keywords the declaration carries, in the language's own words: `async`,
    /// `unsafe`, `pure`. The spelling is preserved and never mapped onto a portable
    /// meaning; absent when empty.
    #[default(Some(Default::default()))]
    pub effects: Option<Vec<String>>,
    /// Facts a provider carries that the model has no field for, under a reverse-domain key.
    /// Keys and values use RFC 8785 canonical JSON. Consumers skip entries they do not
    /// implement.
    pub extensions: Option<serde_json::Value>,
    /// A language name and its optional dialect, joined by `:`. `sql` and `sql:postgresql` are two languages with two symbol spaces.
    pub language: String,
    /// Symbols named inside `display`, each with the byte range of `display` that names it,
    /// so a renderer can turn the rendered text into links. Absent when empty.
    #[default(Some(Default::default()))]
    pub links: Option<Vec<SignatureLink>>,
    /// Declared parameters, in source order. Absent when empty.
    #[default(Some(Default::default()))]
    pub parameters: Option<Vec<Parameter>>,
    /// The implicit first parameter - `self`, `this`. Absent for a free function, and for
    /// languages that have no such thing.
    pub receiver: Option<Parameter>,
    /// What the call yields, absent when empty. An array because a language may return
    /// several values, and because a declared and an inferred return are separate
    /// bindings.
    #[default(Some(Default::default()))]
    pub returns: Option<Vec<TypeBinding>>,
    /// Types this form declares it can raise. Absent when empty.
    #[default(Some(Default::default()))]
    pub throws: Option<Vec<TypeExpression>>,
    /// The generic parameters this form declares, each as the symbol that declares it.
    /// Absent when empty.
    #[default(Some(Default::default()))]
    pub type_parameters: Option<Vec<String>>,
}
/// One parameter of a `Signature`: what it is called, the types bound to it, and how a call
/// may pass it. A receiver is one of these too, held in its own field because it has no
/// position in the parameter list.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(default)]
pub struct Parameter {
    /// The default value as written in the source. Absent where there is none.
    pub default: Option<String>,
    /// Facts a provider carries that the model has no field for, under a reverse-domain key.
    /// Keys and values use RFC 8785 canonical JSON. Consumers skip entries they do not
    /// implement.
    pub extensions: Option<serde_json::Value>,
    /// What the parameter is called. Absent where the language allows an unnamed one, as
    /// a positional parameter in a function type.
    pub name: Option<String>,
    /// Where this parameter is written in the source.
    pub node: Option<NodeId>,
    /// Whether a call may leave it out.
    pub optional: bool,
    /// What it accepts, absent when empty. An array because a declared type and an
    /// inferred one are separate bindings.
    #[default(Some(Default::default()))]
    pub types: Option<Vec<TypeBinding>>,
    /// Whether it absorbs the arguments that follow - `*args`, `...rest`.
    pub variadic: bool,
}
/// Identity of one syntax-tree node. The byte range locates the node in the tree the request
/// targets; the fragment after `#` is its witness - the first eight lowercase hex characters
/// of the SHA-256 of the node's source bytes. The identity describes the node in the
/// revision the response names.
pub type NodeId = String;
/// One type a symbol carries, together with the role it plays for that symbol.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct TypeBinding {
    /// Where the type fact came from. A declared type and an inferred one can both be present
    /// and disagree, which is the interesting case.
    pub origin: TypeBindingOrigin,
    /// What this type is to the symbol that carries it.
    pub role: TypeBindingRole,
    /// How a type is written in the source, plus the symbol that declares it when one does. A
    /// type with a declaration resolves to that symbol; a structural type - `string | null`,
    /// `{ a: string }` - has the spelling and nothing to resolve to.
    #[serde(rename = "type")]
    pub r#type: TypeExpression,
}
/// What this type is to the symbol that carries it.
#[derive(Debug, Clone, PartialEq, Eq, Hash, oas3_gen_support::Default)]
pub enum TypeBindingRole {
    /// The type of the implicit first parameter.
    #[default]
    Receiver,
    /// The type a parameter accepts.
    Parameter,
    /// The type a call yields.
    Return,
    /// The type a field holds.
    Field,
    /// A constraint on a type parameter.
    Bound,
    /// The type of a collection's entries.
    Element,
    /// The type a map is indexed by.
    Key,
    /// The type of the failure a fallible result carries.
    Error,
    /// The type an alias or wrapper stands for.
    Underlying,
    /// The type a generator produces per step.
    Yielded,
    /// The type awaiting the value resolves to.
    Awaited,
    /// The type that tags which variant a value holds.
    Discriminant,
}
impl core::fmt::Display for TypeBindingRole {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Receiver => write!(f, "receiver"),
            Self::Parameter => write!(f, "parameter"),
            Self::Return => write!(f, "return"),
            Self::Field => write!(f, "field"),
            Self::Bound => write!(f, "bound"),
            Self::Element => write!(f, "element"),
            Self::Key => write!(f, "key"),
            Self::Error => write!(f, "error"),
            Self::Underlying => write!(f, "underlying"),
            Self::Yielded => write!(f, "yielded"),
            Self::Awaited => write!(f, "awaited"),
            Self::Discriminant => write!(f, "discriminant"),
        }
    }
}
impl<'de> serde::Deserialize<'de> for TypeBindingRole {
    fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_ascii_lowercase().as_str() {
            "receiver" => Ok(TypeBindingRole::Receiver),
            "parameter" => Ok(TypeBindingRole::Parameter),
            "return" => Ok(TypeBindingRole::Return),
            "field" => Ok(TypeBindingRole::Field),
            "bound" => Ok(TypeBindingRole::Bound),
            "element" => Ok(TypeBindingRole::Element),
            "key" => Ok(TypeBindingRole::Key),
            "error" => Ok(TypeBindingRole::Error),
            "underlying" => Ok(TypeBindingRole::Underlying),
            "yielded" => Ok(TypeBindingRole::Yielded),
            "awaited" => Ok(TypeBindingRole::Awaited),
            "discriminant" => Ok(TypeBindingRole::Discriminant),
            _ => {
                Err(
                    serde::de::Error::unknown_variant(
                        &s,
                        &[
                            "receiver",
                            "parameter",
                            "return",
                            "field",
                            "bound",
                            "element",
                            "key",
                            "error",
                            "underlying",
                            "yielded",
                            "awaited",
                            "discriminant",
                        ],
                    ),
                )
            }
        }
    }
}
/// Where the type fact came from. A declared type and an inferred one can both be present
/// and disagree, which is the interesting case.
#[derive(Debug, Clone, PartialEq, Eq, Hash, oas3_gen_support::Default)]
pub enum TypeBindingOrigin {
    /// Written in the source by the author.
    #[default]
    Declared,
    /// Worked out by the provider from usage.
    Inferred,
    /// Required by the surrounding context.
    Expected,
}
impl core::fmt::Display for TypeBindingOrigin {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Declared => write!(f, "declared"),
            Self::Inferred => write!(f, "inferred"),
            Self::Expected => write!(f, "expected"),
        }
    }
}
impl<'de> serde::Deserialize<'de> for TypeBindingOrigin {
    fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_ascii_lowercase().as_str() {
            "declared" => Ok(TypeBindingOrigin::Declared),
            "inferred" => Ok(TypeBindingOrigin::Inferred),
            "expected" => Ok(TypeBindingOrigin::Expected),
            _ => {
                Err(
                    serde::de::Error::unknown_variant(
                        &s,
                        &["declared", "inferred", "expected"],
                    ),
                )
            }
        }
    }
}
/// How a type is written in the source, plus the symbol that declares it when one does. A
/// type with a declaration resolves to that symbol; a structural type - `string | null`,
/// `{ a: string }` - has the spelling and nothing to resolve to.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct TypeExpression {
    /// Facts a provider carries that the model has no field for, under a reverse-domain key.
    /// Keys and values use RFC 8785 canonical JSON. Consumers skip entries they do not
    /// implement.
    pub extensions: Option<serde_json::Value>,
    /// A language name and its optional dialect, joined by `:`. `sql` and `sql:postgresql` are two languages with two symbol spaces.
    pub language: String,
    /// The symbol that declares this type, where one does. Absent for a structural type,
    /// which has a spelling and nothing to open.
    pub resolved: Option<SymbolId>,
    /// The type as it is written: `Optional[Config]`, `&mut [u8]`, `string | null`.
    pub source: String,
}
/// One symbol named inside a rendered signature, with the byte range of that rendering which
/// names it.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct SignatureLink {
    /// Half-open UTF-8 byte offsets over authoritative UTF-8 source. Every provider converts
    /// from whatever its toolchain counts in at its own boundary, so two toolchains' column
    /// numbers arrive here on the same scale. No JSON Schema keyword can tie one field to
    /// another, so that `end` is never below `start` is asserted by the surface
    /// validation tests instead.
    pub range: TextRange,
    /// Identity of one symbol. The name after the language is the provider's stable qualified
    /// name for the declaration; where the language derives module identity from the file path,
    /// as TypeScript does, that path is part of the name. A `~N` suffix separates declarations
    /// the qualified name alone cannot, such as overloads that dispatch separately. A move can
    /// change the identity when the language includes module path in that qualified name.
    pub symbol: String,
}
/// Half-open UTF-8 byte offsets over authoritative UTF-8 source. Every provider converts
/// from whatever its toolchain counts in at its own boundary, so two toolchains' column
/// numbers arrive here on the same scale. No JSON Schema keyword can tie one field to
/// another, so that `end` is never below `start` is asserted by the surface
/// validation tests instead.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct TextRange {
    /// One past the last byte. Equal to `start` for an empty range, which is how a position
    /// between two bytes is spelled.
    pub end: u64,
    /// First byte of the range, counted from the start of the file.
    pub start: u64,
}
/// One package the workspace depends on, as its manifests and lockfiles state it.
///
/// Entries order by manager, then name, then the selector they state: a declared
/// requirement before an exact version.
#[serde_with::skip_serializing_none]
#[derive(
    Debug,
    Clone,
    PartialEq,
    Serialize,
    Deserialize,
    validator::Validate,
    oas3_gen_support::Default
)]
#[serde(deny_unknown_fields)]
pub struct PackageContextEntry {
    /// Whether a global package index can answer for one package.
    pub availability: PackageAvailability,
    /// Package manager or ecosystem name.
    #[validate(length(max = 128u64))]
    pub manager: String,
    /// Package name in that ecosystem.
    #[validate(length(max = 4_096u64))]
    pub name: String,
    /// The version requirement a manifest declares. Absent when a lockfile pins the
    /// version.
    #[validate(length(max = 4_096u64))]
    pub requirement: Option<String>,
    /// The exact version a lockfile pins. Absent when only a manifest names the package.
    #[validate(length(max = 4_096u64))]
    pub version: Option<String>,
}
/// Whether a global package index can answer for one package.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, oas3_gen_support::Default)]
pub enum PackageAvailability {
    /// The entry names a package a public registry serves: crates.io, npm, or the
    /// Python Package Index.
    #[serde(rename = "canonical")]
    #[default]
    Canonical,
    /// The entry names a path, git, or custom-registry package only this machine can
    /// answer for.
    #[serde(rename = "local_only")]
    LocalOnly,
}
impl core::fmt::Display for PackageAvailability {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Canonical => write!(f, "canonical"),
            Self::LocalOnly => write!(f, "local_only"),
        }
    }
}
impl<'de> serde::Deserialize<'de> for PackageAvailability {
    fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_ascii_lowercase().as_str() {
            "canonical" => Ok(PackageAvailability::Canonical),
            "local_only" => Ok(PackageAvailability::LocalOnly),
            _ => Err(serde::de::Error::unknown_variant(&s, &["canonical", "local_only"])),
        }
    }
}
/// Publication format used by the package index.
#[derive(Debug, Clone, PartialEq, Eq, Hash, oas3_gen_support::Default)]
pub enum PublicationFormat {
    #[default]
    RiftPackageIndexV1,
    Unknown,
}
impl core::fmt::Display for PublicationFormat {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::RiftPackageIndexV1 => write!(f, "rift-package-index-v1"),
            Self::Unknown => write!(f, "unknown"),
        }
    }
}
impl<'de> serde::Deserialize<'de> for PublicationFormat {
    fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_ascii_lowercase().as_str() {
            "rift-package-index-v1" => Ok(PublicationFormat::RiftPackageIndexV1),
            "unknown" => Ok(PublicationFormat::Unknown),
            _ => Ok(PublicationFormat::Unknown),
        }
    }
}
/// One bounded member from the parsed query.
#[derive(
    Debug,
    Clone,
    PartialEq,
    Serialize,
    validator::Validate,
    oas3_gen_support::Default
)]
#[serde(deny_unknown_fields)]
pub struct QueryTerm {
    /// One parsed query term or phrase.
    #[validate(length(min = 1u64, max = 256u64))]
    pub text: String,
    /// Whether the caller quoted this term.
    pub phrase: bool,
    /// Whether the remote index widens this term as a prefix.
    pub prefix: bool,
}
/// One condition the caller must account for.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct Warning {
    /// Stable warning code.
    pub code: WarningCode,
    /// Bounded explanation for the warning.
    pub detail: Option<String>,
    /// Additional properties not defined in the schema.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
/// Active server ceilings for requests and responses.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct CapabilityBounds {
    pub request_body_bytes_max: i64,
    pub response_body_bytes_max: i64,
    pub dependency_entries_max: i64,
    pub query_bytes_max: i64,
    pub query_terms_max: i64,
    pub query_term_bytes_max: i64,
    pub identifiers_max: i64,
    pub identifier_bytes_max: i64,
    pub packages_max: i64,
    pub page_limit_min: i64,
    pub page_limit_max: i64,
    pub page_limit_default: i64,
    pub cursor_bytes_max: i64,
    pub candidate_pool_max: i64,
    pub warnings_max: i64,
    pub source_bytes_max: i64,
    /// Additional properties not defined in the schema.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
/// Capabilities and active bounds for the package API.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct Capabilities {
    /// Supported package managers.
    pub supported_package_managers: Vec<String>,
    /// Supported API features.
    pub supported_features: Vec<String>,
    /// Publication format used by the package index.
    pub publication_format: PublicationFormat,
    /// Analyzer revision used to produce declarations.
    pub analyzer_revision: String,
    /// Corpus revision used to answer reads.
    pub corpus_revision: String,
    /// Fields required for package search.
    pub required_search_fields: Vec<String>,
    /// Active server ceilings for requests and responses.
    pub bounds: CapabilityBounds,
    /// Additional properties not defined in the schema.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
/// Canonical dependency context submitted for package resolution.
#[derive(
    Debug,
    Clone,
    PartialEq,
    Serialize,
    validator::Validate,
    oas3_gen_support::Default
)]
#[serde(deny_unknown_fields)]
pub struct PackageResolutionRequest {
    /// Canonical dependency context entries.
    #[validate(length(max = 20_000u64), nested)]
    pub entries: Vec<PackageContextEntry>,
}
/// One submitted requirement paired with its resolved package.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct ResolvedRequirement {
    /// One package the workspace depends on, as its manifests and lockfiles state it.
    ///
    /// Entries order by manager, then name, then the selector they state: a declared
    /// requirement before an exact version.
    pub entry: PackageContextEntry,
    /// One package as its package manager identifies it.
    pub package: PackageIdentity,
    /// Additional properties not defined in the schema.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
/// Resolution result accounting for each submitted entry.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct PackageResolutionResponse {
    /// Exact packages available in the global index.
    pub available_exact: Vec<PackageIdentity>,
    /// Requirements resolved to exact packages.
    pub resolved_requirements: Vec<ResolvedRequirement>,
    /// Exact packages absent from the global index.
    pub missing_exact: Vec<PackageIdentity>,
    /// Requirements absent from the global index.
    pub missing_requirements: Vec<PackageContextEntry>,
    /// Additional properties not defined in the schema.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
/// Structured package declaration search query.
#[serde_with::skip_serializing_none]
#[derive(
    Debug,
    Clone,
    PartialEq,
    Serialize,
    validator::Validate,
    oas3_gen_support::Default
)]
#[serde(deny_unknown_fields)]
pub struct PackageSearchRequest {
    /// Original query text.
    #[validate(length(min = 1u64, max = 4_096u64))]
    pub query: String,
    /// Ordered parsed query members.
    #[validate(length(min = 1u64, max = 32u64), nested)]
    pub terms: Vec<QueryTerm>,
    /// Ordered extracted identifiers.
    #[validate(length(max = 16u64))]
    pub identifiers: Vec<String>,
    /// Optional fields to include.
    #[validate(length(max = 1u64))]
    pub include: Option<Vec<String>>,
    /// Selected exact package versions.
    #[validate(length(max = 20_000u64), nested)]
    pub packages: Vec<PackageIdentity>,
    /// Ranking phase to execute.
    pub phase: PackageSearchRequestPhase,
}
/// Match class established for one declaration identifier.
#[derive(Debug, Clone, PartialEq, Eq, Hash, oas3_gen_support::Default)]
pub enum IdentifierMatchClass {
    #[default]
    QualifiedExact,
    NameExact,
    NamePrefix,
    Substring,
    Unknown,
}
impl core::fmt::Display for IdentifierMatchClass {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::QualifiedExact => write!(f, "qualified_exact"),
            Self::NameExact => write!(f, "name_exact"),
            Self::NamePrefix => write!(f, "name_prefix"),
            Self::Substring => write!(f, "substring"),
            Self::Unknown => write!(f, "unknown"),
        }
    }
}
impl<'de> serde::Deserialize<'de> for IdentifierMatchClass {
    fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_ascii_lowercase().as_str() {
            "qualified_exact" => Ok(IdentifierMatchClass::QualifiedExact),
            "name_exact" => Ok(IdentifierMatchClass::NameExact),
            "name_prefix" => Ok(IdentifierMatchClass::NamePrefix),
            "substring" => Ok(IdentifierMatchClass::Substring),
            "unknown" => Ok(IdentifierMatchClass::Unknown),
            _ => Ok(IdentifierMatchClass::Unknown),
        }
    }
}
/// One public package declaration returned by search.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct PackageSearchHit {
    /// One package as its package manager identifies it.
    pub package: PackageIdentity,
    /// Readable Symbol assembled from normalized Contributions. Source structure lives in Node
    /// and is connected through Relationship.
    pub symbol: Symbol,
    /// Stable identity of one source unit in the source catalog: a resolver identity, then that
    /// resolver's canonical unit key in canonical percent-encoding - for the project resolver, the
    /// project-relative path, as `rift://source/project/src/lib.rs`. An identity derives from its
    /// resolver's canonical human-readable key; digests appear on the wire only as short witnesses
    /// where byte-identity is required.
    pub unit: String,
    /// Half-open UTF-8 byte offsets over authoritative UTF-8 source. Every provider converts
    /// from whatever its toolchain counts in at its own boundary, so two toolchains' column
    /// numbers arrive here on the same scale. No JSON Schema keyword can tie one field to
    /// another, so that `end` is never below `start` is asserted by the surface
    /// validation tests instead.
    pub range: TextRange,
    /// One-based source line containing the declaration.
    pub line: i64,
    /// Fields that contributed to ranking.
    pub contributing_fields: Vec<PackageSearchHitContributingField>,
    /// Match class established for one declaration identifier.
    pub match_class: IdentifierMatchClass,
    /// Optional declaration source excerpt.
    pub source: Option<String>,
    /// Additional properties not defined in the schema.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
/// One ranked page of package declarations.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct PackageSearchPage {
    /// Ranked package declarations.
    pub items: Vec<PackageSearchHit>,
    /// Opaque cursor for the next page.
    pub next_cursor: Option<String>,
    /// Warnings attached to this page.
    pub warnings: Vec<Warning>,
    /// Publication format used by the package index.
    pub publication_format: PublicationFormat,
    /// Analyzer revision used for this page.
    pub analyzer_revision: String,
    /// Corpus revision used for this page.
    pub corpus_revision: String,
    /// Additional properties not defined in the schema.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
/// Package declaration lookup query.
#[serde_with::skip_serializing_none]
#[derive(
    Debug,
    Clone,
    PartialEq,
    Serialize,
    validator::Validate,
    oas3_gen_support::Default
)]
#[serde(deny_unknown_fields)]
pub struct PackageSymbolRequest {
    /// Declaration name to look up.
    #[validate(length(min = 1u64, max = 4_096u64))]
    pub name: String,
    /// Optional language filter.
    pub language: Option<Language>,
    /// Optional fields to include.
    #[validate(length(max = 1u64))]
    pub include: Option<Vec<String>>,
    /// Selected exact package versions.
    #[validate(length(max = 20_000u64), nested)]
    pub packages: Vec<PackageIdentity>,
}
/// One package declaration returned by symbol lookup.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct PackageSymbol {
    /// One package as its package manager identifies it.
    pub package: PackageIdentity,
    /// Readable Symbol assembled from normalized Contributions. Source structure lives in Node
    /// and is connected through Relationship.
    pub symbol: Symbol,
    /// Stable identity of one source unit in the source catalog: a resolver identity, then that
    /// resolver's canonical unit key in canonical percent-encoding - for the project resolver, the
    /// project-relative path, as `rift://source/project/src/lib.rs`. An identity derives from its
    /// resolver's canonical human-readable key; digests appear on the wire only as short witnesses
    /// where byte-identity is required.
    pub unit: String,
    /// Half-open UTF-8 byte offsets over authoritative UTF-8 source. Every provider converts
    /// from whatever its toolchain counts in at its own boundary, so two toolchains' column
    /// numbers arrive here on the same scale. No JSON Schema keyword can tie one field to
    /// another, so that `end` is never below `start` is asserted by the surface
    /// validation tests instead.
    pub range: TextRange,
    /// One-based source line containing the declaration.
    pub line: i64,
    /// Match class established for one declaration identifier.
    pub match_class: IdentifierMatchClass,
    /// Optional declaration source excerpt.
    pub source: Option<String>,
    /// Additional properties not defined in the schema.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
/// One page of package declarations.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct PackageSymbolPage {
    /// Package declarations.
    pub items: Vec<PackageSymbol>,
    /// Opaque cursor for the next page.
    pub next_cursor: Option<String>,
    /// Warnings attached to this page.
    pub warnings: Vec<Warning>,
    /// Publication format used by the package index.
    pub publication_format: PublicationFormat,
    /// Analyzer revision used for this page.
    pub analyzer_revision: String,
    /// Corpus revision used for this page.
    pub corpus_revision: String,
    /// Additional properties not defined in the schema.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
/// RFC 9457 problem details for an application error.
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub struct ProblemDetails {
    #[serde(rename = "type")]
    pub r#type: String,
    pub title: String,
    pub status: i64,
    pub detail: String,
    pub instance: Option<String>,
    /// Additional properties not defined in the schema.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}
/// Returns supported package managers, features, publication revisions, and active bounds.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct GetCapabilitiesRequest {}
impl GetCapabilitiesRequest {
    /// Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetCapabilitiesResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let data = oas3_gen_support::Diagnostics::<
                Capabilities,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetCapabilitiesResponse::Ok(data));
        }
        if status == http::StatusCode::NOT_MODIFIED {
            let _ = req.bytes().await?;
            return Ok(GetCapabilitiesResponse::NotModified);
        }
        if status == http::StatusCode::BAD_REQUEST {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetCapabilitiesResponse::BadRequest(data));
        }
        if status == http::StatusCode::UNAUTHORIZED {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetCapabilitiesResponse::Unauthorized(data));
        }
        if status == http::StatusCode::FORBIDDEN {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetCapabilitiesResponse::Forbidden(data));
        }
        if status == http::StatusCode::NOT_ACCEPTABLE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetCapabilitiesResponse::NotAcceptable(data));
        }
        if status == http::StatusCode::TOO_MANY_REQUESTS {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetCapabilitiesResponse::TooManyRequests(data));
        }
        if status == http::StatusCode::INTERNAL_SERVER_ERROR {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetCapabilitiesResponse::InternalServerError(data));
        }
        if status == http::StatusCode::BAD_GATEWAY {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetCapabilitiesResponse::BadGateway(data));
        }
        if status == http::StatusCode::SERVICE_UNAVAILABLE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetCapabilitiesResponse::ServiceUnavailable(data));
        }
        if status == http::StatusCode::GATEWAY_TIMEOUT {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(GetCapabilitiesResponse::GatewayTimeout(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetCapabilitiesResponse::Unknown);
    }
}
/// Response types for getCapabilities
#[derive(Debug, Clone)]
pub enum GetCapabilitiesResponse {
    ///200: Capabilities and active bounds.
    Ok(Capabilities),
    ///304: The cached capability representation has not changed.
    NotModified,
    ///400: Request JSON, query parameters, or field relationships are invalid.
    BadRequest(ProblemDetails),
    ///401: Authentication is required or credentials are invalid.
    Unauthorized(ProblemDetails),
    ///403: Credentials do not permit this operation.
    Forbidden(ProblemDetails),
    ///406: The server cannot produce an accepted media type.
    NotAcceptable(ProblemDetails),
    ///429: The request rate limit is exhausted.
    TooManyRequests(ProblemDetails),
    ///500: The server encountered an unexpected failure.
    InternalServerError(ProblemDetails),
    ///502: The server received an invalid upstream response.
    BadGateway(ProblemDetails),
    ///503: The service is temporarily unavailable.
    ServiceUnavailable(ProblemDetails),
    ///504: The upstream request timed out.
    GatewayTimeout(ProblemDetails),
    ///default: Unknown response
    Unknown,
}
/// Classifies canonical exact versions and declared requirements against indexed package versions.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct ResolvePackageContextRequest {
    /// Canonical package context.
    #[validate(nested)]
    pub body: PackageResolutionRequest,
}
impl ResolvePackageContextRequest {
    /// Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<ResolvePackageContextResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let data = oas3_gen_support::Diagnostics::<
                PackageResolutionResponse,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ResolvePackageContextResponse::Ok(data));
        }
        if status == http::StatusCode::BAD_REQUEST {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ResolvePackageContextResponse::BadRequest(data));
        }
        if status == http::StatusCode::UNAUTHORIZED {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ResolvePackageContextResponse::Unauthorized(data));
        }
        if status == http::StatusCode::FORBIDDEN {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ResolvePackageContextResponse::Forbidden(data));
        }
        if status == http::StatusCode::NOT_ACCEPTABLE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ResolvePackageContextResponse::NotAcceptable(data));
        }
        if status == http::StatusCode::PAYLOAD_TOO_LARGE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ResolvePackageContextResponse::ContentTooLarge(data));
        }
        if status == http::StatusCode::UNSUPPORTED_MEDIA_TYPE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ResolvePackageContextResponse::UnsupportedMediaType(data));
        }
        if status == http::StatusCode::TOO_MANY_REQUESTS {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ResolvePackageContextResponse::TooManyRequests(data));
        }
        if status == http::StatusCode::INTERNAL_SERVER_ERROR {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ResolvePackageContextResponse::InternalServerError(data));
        }
        if status == http::StatusCode::BAD_GATEWAY {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ResolvePackageContextResponse::BadGateway(data));
        }
        if status == http::StatusCode::SERVICE_UNAVAILABLE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ResolvePackageContextResponse::ServiceUnavailable(data));
        }
        if status == http::StatusCode::GATEWAY_TIMEOUT {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ResolvePackageContextResponse::GatewayTimeout(data));
        }
        let _ = req.bytes().await?;
        return Ok(ResolvePackageContextResponse::Unknown);
    }
}
/// Response types for resolvePackageContext
#[derive(Debug, Clone)]
pub enum ResolvePackageContextResponse {
    ///200: Resolution result accounting for every submitted entry.
    Ok(PackageResolutionResponse),
    ///400: Request JSON, query parameters, or field relationships are invalid.
    BadRequest(ProblemDetails),
    ///401: Authentication is required or credentials are invalid.
    Unauthorized(ProblemDetails),
    ///403: Credentials do not permit this operation.
    Forbidden(ProblemDetails),
    ///406: The server cannot produce an accepted media type.
    NotAcceptable(ProblemDetails),
    ///413: The request body exceeds the request body bound.
    ContentTooLarge(ProblemDetails),
    ///415: The request media type is unsupported.
    UnsupportedMediaType(ProblemDetails),
    ///429: The request rate limit is exhausted.
    TooManyRequests(ProblemDetails),
    ///500: The server encountered an unexpected failure.
    InternalServerError(ProblemDetails),
    ///502: The server received an invalid upstream response.
    BadGateway(ProblemDetails),
    ///503: The service is temporarily unavailable.
    ServiceUnavailable(ProblemDetails),
    ///504: The upstream request timed out.
    GatewayTimeout(ProblemDetails),
    ///default: Unknown response
    Unknown,
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug,
    Clone,
    PartialEq,
    Serialize,
    validator::Validate,
    oas3_gen_support::Default
)]
pub struct SearchPackagesRequestQuery {
    /// Maximum entries in one page.
    #[validate(range(min = 1i64, max = 200i64))]
    #[default(Some(100i64))]
    pub limit: Option<i64>,
    /// Opaque cursor for the next page.
    #[validate(length(max = 4_096u64))]
    pub cursor: Option<String>,
}
/// Returns one ranked declaration page from selected exact package versions.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct SearchPackagesRequest {
    #[validate(nested)]
    pub query: SearchPackagesRequestQuery,
    /// Structured package search query.
    #[validate(nested)]
    pub body: PackageSearchRequest,
}
impl SearchPackagesRequest {
    /// Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<SearchPackagesResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let data = oas3_gen_support::Diagnostics::<
                PackageSearchPage,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(SearchPackagesResponse::Ok(data));
        }
        if status == http::StatusCode::BAD_REQUEST {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(SearchPackagesResponse::BadRequest(data));
        }
        if status == http::StatusCode::UNAUTHORIZED {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(SearchPackagesResponse::Unauthorized(data));
        }
        if status == http::StatusCode::FORBIDDEN {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(SearchPackagesResponse::Forbidden(data));
        }
        if status == http::StatusCode::NOT_ACCEPTABLE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(SearchPackagesResponse::NotAcceptable(data));
        }
        if status == http::StatusCode::PAYLOAD_TOO_LARGE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(SearchPackagesResponse::ContentTooLarge(data));
        }
        if status == http::StatusCode::UNSUPPORTED_MEDIA_TYPE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(SearchPackagesResponse::UnsupportedMediaType(data));
        }
        if status == http::StatusCode::TOO_MANY_REQUESTS {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(SearchPackagesResponse::TooManyRequests(data));
        }
        if status == http::StatusCode::INTERNAL_SERVER_ERROR {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(SearchPackagesResponse::InternalServerError(data));
        }
        if status == http::StatusCode::BAD_GATEWAY {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(SearchPackagesResponse::BadGateway(data));
        }
        if status == http::StatusCode::SERVICE_UNAVAILABLE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(SearchPackagesResponse::ServiceUnavailable(data));
        }
        if status == http::StatusCode::GATEWAY_TIMEOUT {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(SearchPackagesResponse::GatewayTimeout(data));
        }
        let _ = req.bytes().await?;
        return Ok(SearchPackagesResponse::Unknown);
    }
}
/// Response types for searchPackages
#[derive(Debug, Clone)]
pub enum SearchPackagesResponse {
    ///200: One ranked package declaration page.
    Ok(PackageSearchPage),
    ///400: Request JSON, query parameters, or field relationships are invalid.
    BadRequest(ProblemDetails),
    ///401: Authentication is required or credentials are invalid.
    Unauthorized(ProblemDetails),
    ///403: Credentials do not permit this operation.
    Forbidden(ProblemDetails),
    ///406: The server cannot produce an accepted media type.
    NotAcceptable(ProblemDetails),
    ///413: The request body exceeds the request body bound.
    ContentTooLarge(ProblemDetails),
    ///415: The request media type is unsupported.
    UnsupportedMediaType(ProblemDetails),
    ///429: The request rate limit is exhausted.
    TooManyRequests(ProblemDetails),
    ///500: The server encountered an unexpected failure.
    InternalServerError(ProblemDetails),
    ///502: The server received an invalid upstream response.
    BadGateway(ProblemDetails),
    ///503: The service is temporarily unavailable.
    ServiceUnavailable(ProblemDetails),
    ///504: The upstream request timed out.
    GatewayTimeout(ProblemDetails),
    ///default: Unknown response
    Unknown,
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug,
    Clone,
    PartialEq,
    Serialize,
    validator::Validate,
    oas3_gen_support::Default
)]
pub struct ListPackageSymbolsRequestQuery {
    /// Maximum entries in one page.
    #[validate(range(min = 1i64, max = 200i64))]
    #[default(Some(100i64))]
    pub limit: Option<i64>,
    /// Opaque cursor for the next page.
    #[validate(length(max = 4_096u64))]
    pub cursor: Option<String>,
}
/// Returns one declaration page from selected exact package versions.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub struct ListPackageSymbolsRequest {
    #[validate(nested)]
    pub query: ListPackageSymbolsRequestQuery,
    /// Package declaration lookup query.
    #[validate(nested)]
    pub body: PackageSymbolRequest,
}
impl ListPackageSymbolsRequest {
    /// Parse the HTTP response into the response enum.
    pub async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<ListPackageSymbolsResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let data = oas3_gen_support::Diagnostics::<
                PackageSymbolPage,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ListPackageSymbolsResponse::Ok(data));
        }
        if status == http::StatusCode::BAD_REQUEST {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ListPackageSymbolsResponse::BadRequest(data));
        }
        if status == http::StatusCode::UNAUTHORIZED {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ListPackageSymbolsResponse::Unauthorized(data));
        }
        if status == http::StatusCode::FORBIDDEN {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ListPackageSymbolsResponse::Forbidden(data));
        }
        if status == http::StatusCode::NOT_ACCEPTABLE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ListPackageSymbolsResponse::NotAcceptable(data));
        }
        if status == http::StatusCode::PAYLOAD_TOO_LARGE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ListPackageSymbolsResponse::ContentTooLarge(data));
        }
        if status == http::StatusCode::UNSUPPORTED_MEDIA_TYPE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ListPackageSymbolsResponse::UnsupportedMediaType(data));
        }
        if status == http::StatusCode::TOO_MANY_REQUESTS {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ListPackageSymbolsResponse::TooManyRequests(data));
        }
        if status == http::StatusCode::INTERNAL_SERVER_ERROR {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ListPackageSymbolsResponse::InternalServerError(data));
        }
        if status == http::StatusCode::BAD_GATEWAY {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ListPackageSymbolsResponse::BadGateway(data));
        }
        if status == http::StatusCode::SERVICE_UNAVAILABLE {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ListPackageSymbolsResponse::ServiceUnavailable(data));
        }
        if status == http::StatusCode::GATEWAY_TIMEOUT {
            let data = oas3_gen_support::Diagnostics::<
                ProblemDetails,
            >::json_with_diagnostics(req)
                .await?;
            return Ok(ListPackageSymbolsResponse::GatewayTimeout(data));
        }
        let _ = req.bytes().await?;
        return Ok(ListPackageSymbolsResponse::Unknown);
    }
}
/// Response types for listPackageSymbols
#[derive(Debug, Clone)]
pub enum ListPackageSymbolsResponse {
    ///200: One package declaration page.
    Ok(PackageSymbolPage),
    ///400: Request JSON, query parameters, or field relationships are invalid.
    BadRequest(ProblemDetails),
    ///401: Authentication is required or credentials are invalid.
    Unauthorized(ProblemDetails),
    ///403: Credentials do not permit this operation.
    Forbidden(ProblemDetails),
    ///406: The server cannot produce an accepted media type.
    NotAcceptable(ProblemDetails),
    ///413: The request body exceeds the request body bound.
    ContentTooLarge(ProblemDetails),
    ///415: The request media type is unsupported.
    UnsupportedMediaType(ProblemDetails),
    ///429: The request rate limit is exhausted.
    TooManyRequests(ProblemDetails),
    ///500: The server encountered an unexpected failure.
    InternalServerError(ProblemDetails),
    ///502: The server received an invalid upstream response.
    BadGateway(ProblemDetails),
    ///503: The service is temporarily unavailable.
    ServiceUnavailable(ProblemDetails),
    ///504: The upstream request timed out.
    GatewayTimeout(ProblemDetails),
    ///default: Unknown response
    Unknown,
}
/// Stable warning code.
#[derive(Debug, Clone, PartialEq, Eq, Hash, oas3_gen_support::Default)]
pub enum WarningCode {
    #[default]
    QueryNarrowed,
    SourceTruncated,
    PublicationChanged,
    CapabilityUnavailable,
    ResultTruncated,
    Unknown,
}
impl core::fmt::Display for WarningCode {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::QueryNarrowed => write!(f, "query_narrowed"),
            Self::SourceTruncated => write!(f, "source_truncated"),
            Self::PublicationChanged => write!(f, "publication_changed"),
            Self::CapabilityUnavailable => write!(f, "capability_unavailable"),
            Self::ResultTruncated => write!(f, "result_truncated"),
            Self::Unknown => write!(f, "unknown"),
        }
    }
}
impl<'de> serde::Deserialize<'de> for WarningCode {
    fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_ascii_lowercase().as_str() {
            "query_narrowed" => Ok(WarningCode::QueryNarrowed),
            "source_truncated" => Ok(WarningCode::SourceTruncated),
            "publication_changed" => Ok(WarningCode::PublicationChanged),
            "capability_unavailable" => Ok(WarningCode::CapabilityUnavailable),
            "result_truncated" => Ok(WarningCode::ResultTruncated),
            "unknown" => Ok(WarningCode::Unknown),
            _ => Ok(WarningCode::Unknown),
        }
    }
}
/// Ranking phase to execute.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, oas3_gen_support::Default)]
pub enum PackageSearchRequestPhase {
    #[serde(rename = "precise")]
    #[default]
    Precise,
    #[serde(rename = "broad")]
    Broad,
}
impl core::fmt::Display for PackageSearchRequestPhase {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Precise => write!(f, "precise"),
            Self::Broad => write!(f, "broad"),
        }
    }
}
impl<'de> serde::Deserialize<'de> for PackageSearchRequestPhase {
    fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_ascii_lowercase().as_str() {
            "precise" => Ok(PackageSearchRequestPhase::Precise),
            "broad" => Ok(PackageSearchRequestPhase::Broad),
            _ => Err(serde::de::Error::unknown_variant(&s, &["precise", "broad"])),
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Hash, oas3_gen_support::Default)]
pub enum PackageSearchHitContributingField {
    #[default]
    Name,
    QualifiedName,
    Documentation,
    Signature,
    DeclarationSource,
    Unknown,
}
impl core::fmt::Display for PackageSearchHitContributingField {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Name => write!(f, "name"),
            Self::QualifiedName => write!(f, "qualified_name"),
            Self::Documentation => write!(f, "documentation"),
            Self::Signature => write!(f, "signature"),
            Self::DeclarationSource => write!(f, "declaration_source"),
            Self::Unknown => write!(f, "unknown"),
        }
    }
}
impl<'de> serde::Deserialize<'de> for PackageSearchHitContributingField {
    fn deserialize<D>(deserializer: D) -> core::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        match s.to_ascii_lowercase().as_str() {
            "name" => Ok(PackageSearchHitContributingField::Name),
            "qualified_name" => Ok(PackageSearchHitContributingField::QualifiedName),
            "documentation" => Ok(PackageSearchHitContributingField::Documentation),
            "signature" => Ok(PackageSearchHitContributingField::Signature),
            "declaration_source" => {
                Ok(PackageSearchHitContributingField::DeclarationSource)
            }
            "unknown" => Ok(PackageSearchHitContributingField::Unknown),
            _ => Ok(PackageSearchHitContributingField::Unknown),
        }
    }
}

