[package]
name = "rift-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "Protocol models and exported schemas for Rift"

[lints]
workspace = true

[dependencies]
percent-encoding.workspace = true
pep440_rs.workspace = true
schemars.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_json_canonicalizer.workspace = true
serde_path_to_error.workspace = true
strum.workspace = true
url.workspace = true

[dev-dependencies]
jsonschema.workspace = true
