//! Generated Rift wire contract.
//!
//! Type generation lands independently. These constants keep canonical root
//! schemas available from crate boundary during workspace construction.

/// Canonical MCP schema generated by protocol package.
pub const MCP_SCHEMA: &str = include_str!("../../mcp.json");

/// Canonical Rift schema generated by protocol package.
pub const RIFT_SCHEMA: &str = include_str!("../../rift.schema.json");
